import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { PageHeader, Panel, Tag } from "@/components/ui-kit";
import { formatCurrency } from "@/lib/finance";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { useGlobalMonth } from "@/hooks/use-global-month";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/calendario")({head:()=>({meta:[{title:"CALENDÁRIO — MULTICAP"},{name:"description",content:"LANÇAMENTOS REAIS ORGANIZADOS POR DATA."}]}),component:CalendarPage});
type Tx={id:string;date:string;description:string;amount:number;category:string;responsible:string;type:string;household_id:string};
type Task={id:string;title:string;due_date:string|null;completed:boolean;household_id:string};
const WEEK=["DOM","SEG","TER","QUA","QUI","SEX","SÁB"];
function heat(value:number){if(value===0)return "bg-secondary/40";if(value<100)return "bg-primary/15";if(value<350)return "bg-primary/35";if(value<900)return "bg-primary/60";return "gradient-primary";}
function CalendarPage(){
 const {month}=useGlobalMonth(); const [selected,setSelected]=useState(1);
 const tx=useHouseholdTable<Tx>("transactions","id,date,description,amount,category,responsible,type,household_id","date"); const tasks=useHouseholdTable<Task>("tasks","id,title,due_date,completed,household_id","due_date");
 const [year,monthNumber]=month.split("-").map(Number); const days=new Date(year,monthNumber,0).getDate(); const first=new Date(year,monthNumber-1,1).getDay();
 const monthly=useMemo(()=>tx.rows.filter(t=>t.date.startsWith(month)),[tx.rows,month]); const selectedKey=`${month}-${String(selected).padStart(2,"0")}`; const dayTx=monthly.filter(t=>t.date===selectedKey); const dayTasks=tasks.rows.filter(t=>t.due_date===selectedKey);
 const spendByDay=useMemo(()=>{const map=new Map<number,number>();monthly.filter(t=>t.type==="DESPESA").forEach(t=>{const d=Number(t.date.slice(-2));map.set(d,(map.get(d)||0)+Number(t.amount));});return map;},[monthly]);
 const monthName=new Date(year,monthNumber-1,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}).toUpperCase();
 return <div className="space-y-5"><PageHeader title="CALENDÁRIO" subtitle="LANÇAMENTOS E TAREFAS REAIS DO MÊS SELECIONADO." action={<Tag tone="primary">{monthName}</Tag>}/><div className="grid gap-4 lg:grid-cols-3"><Panel className="lg:col-span-2"><div className="mb-2 grid grid-cols-7 gap-1.5">{WEEK.map(d=><span key={d} className="label-caps text-center text-[10px] text-muted-foreground">{d}</span>)}</div><div className="grid grid-cols-7 gap-1.5">{Array.from({length:first}).map((_,i)=><span key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>i+1).map(day=>{const spend=spendByDay.get(day)||0;return <button key={day} onClick={()=>setSelected(day)} className={cn("flex aspect-square flex-col items-center justify-center rounded-xl border border-border/60 text-[11px] transition-all",heat(spend),selected===day&&"ring-2 ring-primary")}><span className="font-semibold">{day}</span>{spend>0&&<span className="text-[8px] opacity-80">{spend>=1000?`${(spend/1000).toFixed(1)}K`:Math.round(spend)}</span>}</button>})}</div><p className="mt-4 text-[10px] text-muted-foreground">OS VALORES DO CALENDÁRIO SÃO CALCULADOS EXCLUSIVAMENTE DOS LANÇAMENTOS REAIS.</p></Panel><Panel title={`${selectedKey} — RESUMO`}><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-border bg-secondary/40 p-3"><p className="label-caps text-[10px] text-muted-foreground">GASTO</p><p className="mt-1 text-sm font-bold text-danger">{formatCurrency(dayTx.filter(t=>t.type==="DESPESA").reduce((s,t)=>s+Number(t.amount),0))}</p></div><div className="rounded-xl border border-border bg-secondary/40 p-3"><p className="label-caps text-[10px] text-muted-foreground">RECEBIDO</p><p className="mt-1 text-sm font-bold text-success">{formatCurrency(dayTx.filter(t=>t.type==="RECEITA").reduce((s,t)=>s+Number(t.amount),0))}</p></div></div><div className="mt-4 space-y-2"><p className="label-caps text-[10px] text-muted-foreground">LANÇAMENTOS</p>{dayTx.length===0?<p className="text-xs text-muted-foreground">NENHUM LANÇAMENTO NESTE DIA.</p>:dayTx.map(t=><div key={t.id} className="flex items-center justify-between rounded-xl border border-border bg-secondary/30 px-3 py-2"><div><p className="label-caps text-[11px]">{t.description}</p><p className="text-[10px] text-muted-foreground">{t.category} · {t.responsible}</p></div><span className={cn("text-sm font-semibold",t.type==="RECEITA"?"text-success":"text-danger")}>{formatCurrency(Number(t.amount))}</span></div>)}</div><div className="mt-4 space-y-2"><p className="label-caps text-[10px] text-muted-foreground">TAREFAS COM PRAZO</p>{dayTasks.length===0?<p className="text-xs text-muted-foreground">NENHUMA TAREFA COM PRAZO NESTE DIA.</p>:dayTasks.map(t=><div key={t.id} className="rounded-xl border border-border bg-secondary/30 px-3 py-2"><p className={cn("label-caps text-[11px]",t.completed&&"line-through")}>{t.title}</p><p className="text-[10px] text-muted-foreground">{t.completed?"CONCLUÍDA":"PENDENTE"}</p></div>)}</div></Panel></div></div>;
}
