import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { PageHeader, Panel, Tag } from "@/components/ui-kit";
import { useAuth } from "@/hooks/use-auth";
import { useHouseholdMembers } from "@/hooks/use-household-members";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/configuracoes")({ head: () => ({ meta: [{ title: "CONFIGURAÇÕES — MULTICAP" }] }), component: SettingsPage });
type Card={id:string;name:string;brand:string|null;last4:string|null;credit_limit:number;close_day:number;due_day:number;household_id:string};
type Category={id:string;name:string;kind:string;household_id:string};
type Payment={id:string;name:string;description:string|null;household_id:string};

function SettingsPage(){
 const {user,profile,refreshProfile}=useAuth();
 const {data:members=[],isLoading:membersLoading}=useHouseholdMembers();
 const cards=useHouseholdTable<Card>("cards","id,name,brand,last4,credit_limit,close_day,due_day,household_id");
 const categories=useHouseholdTable<Category>("categories","id,name,kind,household_id","name");
 const payments=useHouseholdTable<Payment>("household_payment_methods","id,name,description,household_id","name");
 const[name,setName]=useState(profile?.name??user?.user_metadata?.full_name??"");
 const[cat,setCat]=useState(""); const[catEdit,setCatEdit]=useState<string|null>(null); const[catName,setCatName]=useState("");
 const[pay,setPay]=useState(""); const[payDesc,setPayDesc]=useState(""); const[payEdit,setPayEdit]=useState<string|null>(null); const[payName,setPayName]=useState(""); const[payDescEdit,setPayDescEdit]=useState("");
 const[cardName,setCardName]=useState(""); const[brand,setBrand]=useState(""); const[last4,setLast4]=useState(""); const[limit,setLimit]=useState(""); const[close,setClose]=useState("28"); const[due,setDue]=useState("5"); const[cardEdit,setCardEdit]=useState<string|null>(null);
 async function saveProfile(){if(!user||!name.trim())return toast.error("INFORME SEU NOME");try{const{error}=await supabase.from("profiles").update({name:name.trim().toUpperCase()}).eq("id",user.id);if(error)throw error;await refreshProfile();toast.success("PERFIL ATUALIZADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ATUALIZAR")}}
 async function addCard(){const n=cardName.trim().toUpperCase();if(!n)return toast.error("INFORME O NOME DO CARTÃO");try{await cards.insert({name:n,brand:brand.trim().toUpperCase()||null,last4:last4.trim()||null,credit_limit:Number(limit)||0,close_day:Number(close)||28,due_day:Number(due)||5});clearCard();toast.success("CARTÃO ADICIONADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ADICIONAR CARTÃO")}}
 async function editCard(){if(!cardEdit)return;const n=cardName.trim().toUpperCase();if(!n)return toast.error("INFORME O NOME DO CARTÃO");try{await cards.update(cardEdit,{name:n,brand:brand.trim().toUpperCase()||null,last4:last4.trim()||null,credit_limit:Number(limit)||0,close_day:Number(close)||28,due_day:Number(due)||5});clearCard();toast.success("CARTÃO ATUALIZADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ATUALIZAR CARTÃO")}}
 function clearCard(){setCardEdit(null);setCardName("");setBrand("");setLast4("");setLimit("");setClose("28");setDue("5")}
 function startCardEdit(c:Card){setCardEdit(c.id);setCardName(c.name);setBrand(c.brand??"");setLast4(c.last4??"");setLimit(String(c.credit_limit??0));setClose(String(c.close_day??28));setDue(String(c.due_day??5));}
 async function addCategory(){const n=cat.trim().toUpperCase();if(!n)return toast.error("INFORME A CATEGORIA");if(categories.rows.some(x=>x.name.toUpperCase()===n))return toast.error("ESSA CATEGORIA JÁ EXISTE");try{await categories.insert({name:n,kind:"DESPESA"});setCat("");toast.success("CATEGORIA ADICIONADA")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ADICIONAR")}}
 async function addPayment(){const n=pay.trim().toUpperCase();if(!n)return toast.error("INFORME O MÉTODO");try{await payments.insert({name:n,description:payDesc.trim()||null});setPay("");setPayDesc("");toast.success("MÉTODO ADICIONADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ADICIONAR")}}
 return <div className="space-y-6"><PageHeader title="CONFIGURAÇÕES" description="GERENCIE SEUS DADOS E CARTÕES"/><Panel title="PERFIL"><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} className="input"/><button onClick={saveProfile}>SALVAR</button></div></Panel><Panel title="CARTÕES"><div className="grid gap-2 md:grid-cols-6"><input placeholder="Nome" value={cardName} onChange={e=>setCardName(e.target.value)}/><input placeholder="Bandeira" value={brand} onChange={e=>setBrand(e.target.value)}/><input placeholder="4 últimos" value={last4} onChange={e=>setLast4(e.target.value)}/><input placeholder="Limite" type="number" value={limit} onChange={e=>setLimit(e.target.value)}/><input placeholder="Fechamento" type="number" value={close} onChange={e=>setClose(e.target.value)}/><input placeholder="Vencimento" type="number" value={due} onChange={e=>setDue(e.target.value)}/></div><div className="flex gap-2 mt-3"><button onClick={cardEdit?editCard:addCard}>{cardEdit?"SALVAR EDIÇÃO":"ADICIONAR CARTÃO"}</button>{cardEdit&&<button onClick={clearCard}>CANCELAR</button>}</div><div className="space-y-2 mt-4">{cards.rows.map(c=><div key={c.id} className="flex items-center justify-between border rounded-lg p-3"><div><strong>{c.name}</strong><div className="text-sm opacity-70">{c.brand??""} {c.last4?`•••• ${c.last4}`:""} · LIMITE R$ {Number(c.credit_limit??0).toFixed(2)} · FECHA {c.close_day} · VENCE {c.due_day}</div></div><div className="flex gap-2"><button onClick={()=>startCardEdit(c)}>EDITAR</button><button onClick={async()=>{try{await cards.remove(c.id);toast.success("CARTÃO EXCLUÍDO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO EXCLUIR")}}}>EXCLUIR</button></div></div>)}</div></Panel><Panel title="CATEGORIAS"><div className="flex gap-2"><input value={cat} onChange={e=>setCat(e.target.value)} placeholder="Nova categoria"/><button onClick={addCategory}>ADICIONAR</button></div></Panel><Panel title="MÉTODOS DE PAGAMENTO"><div className="flex gap-2"><input value={pay} onChange={e=>setPay(e.target.value)} placeholder="Novo método"/><input value={payDesc} onChange={e=>setPayDesc(e.target.value)} placeholder="Descrição"/><button onClick={addPayment}>ADICIONAR</button></div></Panel><Panel title="MEMBROS"><div>{membersLoading?"CARREGANDO...":members.map((m:any)=><Tag key={m.id}>{m.name}</Tag>)}</div></Panel></div>
}
