import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { PageHeader, Panel, StatCard, Tag, PersonDot } from "@/components/ui-kit";
import { formatCurrency } from "@/lib/finance";
import { useHouseholdTable } from "@/hooks/use-household-data";

export const Route = createFileRoute("/custos-fixos")({ head: () => ({ meta: [{ title: "CUSTOS FIXOS — MULTICAP" }] }), component: FixedCostsPage });
const MONTHS = ["JAN","FEV","MAR","ABR","MAI","JUN","JUL","AGO","SET","OUT","NOV","DEZ"];
type Row = { id:string; name:string; amount:number; category:string; due_day:number; months:boolean[]; responsible:string; household_id:string };
function FixedCostsPage() {
  const { rows, insert, update, remove, isLoading } = useHouseholdTable<Row>("fixed_costs", "id,name,amount,category,due_day,months,responsible,household_id");
  const [name,setName]=useState(""); const [amount,setAmount]=useState(""); const [category,setCategory]=useState("MORADIA"); const [day,setDay]=useState("5"); const [responsible,setResponsible]=useState("AMBAS");
  const monthly = rows.filter(f=>f.months[new Date().getMonth()]).reduce((s,f)=>s+Number(f.amount),0);
  const annual = rows.reduce((s,f)=>s+Number(f.amount)*f.months.filter(Boolean).length,0);
  async function add(){ const value=Number(amount.replace(",",".")); if(!name.trim()||!value||value<0)return toast.error("PREENCHA NOME E VALOR"); try{await insert({name:name.trim().toUpperCase(),amount:value,category,due_day:Math.max(1,Math.min(31,Number(day)||5)),months:Array(12).fill(true),responsible,pay_method:"BOLETO"});setName("");setAmount("");toast.success("CUSTO FIXO SALVO")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar")}}
  async function toggleMonth(f:Row,i:number){try{const months=[...f.months];months[i]=!months[i];await update(f.id,{months})}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível atualizar")}}
  async function del(f:Row){if(!window.confirm(`Excluir ${f.name}?`))return;try{await remove(f.id);toast.success("CUSTO FIXO EXCLUÍDO")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível excluir")}}
  return <div className="space-y-5"><PageHeader title="CUSTOS FIXOS" subtitle="Despesas recorrentes e recorrência anual."/><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><StatCard label="TOTAL DO MÊS" value={formatCurrency(monthly)} tone="primary"/><StatCard label="CUSTO ANUAL ESTIMADO" value={formatCurrency(annual)} tone="info"/><StatCard label="DESPESAS ATIVAS" value={String(rows.length)} tone="success"/></div>
  <Panel title="NOVO CUSTO FIXO"><div className="grid gap-3 md:grid-cols-5"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Valor" inputMode="decimal" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"><option>MORADIA</option><option>ALIMENTAÇÃO</option><option>TRANSPORTE</option><option>SAÚDE</option><option>IMPOSTOS</option><option>OUTROS</option></select><input value={day} onChange={e=>setDay(e.target.value)} placeholder="Dia" type="number" min="1" max="31" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><button onClick={add} className="gradient-primary rounded-xl px-4 py-2.5 text-[11px] text-primary-foreground">SALVAR</button></div></Panel>
  <Panel title="DESPESAS RECORRENTES">{isLoading?<p className="py-8 text-center text-sm text-muted-foreground">Carregando...</p>:rows.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Nenhum custo fixo cadastrado.</p>:<div className="space-y-3">{rows.map(f=><div key={f.id} className="rounded-xl border border-border bg-secondary/30 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="label-caps text-[12px]">{f.name}</p><div className="mt-1 flex items-center gap-2"><Tag>{f.category}</Tag><Tag tone="warning">DIA {f.due_day}</Tag><PersonDot name={f.responsible}/></div></div><div className="text-right"><p className="text-sm font-bold">{formatCurrency(Number(f.amount))}</p><button onClick={()=>del(f)} className="text-[10px] text-danger">EXCLUIR</button></div></div><div className="mt-3 grid grid-cols-12 gap-1">{MONTHS.map((m,i)=><button key={m} onClick={()=>toggleMonth(f,i)} className={`label-caps rounded-md py-1 text-center text-[8px] ${f.months[i]?"gradient-primary text-primary-foreground":"bg-background text-muted-foreground"}`}>{m}</button>)}</div></div>)}</div>}</Panel></div>;
}
