import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Building2, Calculator, ChefHat, Package, Factory, ShoppingCart, Wallet, Users, Plus, Save, AlertTriangle, ArrowRight } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader, Panel, StatCard, Tag } from "@/components/ui-kit";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useAuth } from "@/hooks/use-auth";

export const Route = createFileRoute("/empresarial")({ head: () => ({ meta: [{ title: "EMPRESARIAL — HARMONY HUB" }] }), component: EmpresarialPage });
type Tab="DASHBOARD"|"EMPRESA"|"INSUMOS"|"RECEITAS"|"PRECIFICAÇÃO"|"FORNECEDORES"|"PRODUÇÃO"|"VENDAS"|"FINANCEIRO";
const tabs:{id:Tab;label:string;icon:typeof Building2}[]=[
{id:"DASHBOARD",label:"DASHBOARD",icon:Wallet},{id:"EMPRESA",label:"EMPRESA",icon:Building2},{id:"INSUMOS",label:"INSUMOS",icon:Package},
{id:"RECEITAS",label:"RECEITAS",icon:ChefHat},{id:"PRECIFICAÇÃO",label:"PRECIFICAÇÃO",icon:Calculator},{id:"FORNECEDORES",label:"FORNECEDORES",icon:Users},
{id:"PRODUÇÃO",label:"PRODUÇÃO / ESTOQUE",icon:Factory},{id:"VENDAS",label:"VENDAS",icon:ShoppingCart},{id:"FINANCEIRO",label:"FINANCEIRO",icon:Wallet}];
type Business={id:string;household_id:string;name:string;legal_name:string|null;document:string|null;tax_regime:string|null;phone:string|null;email:string|null;address:string|null;city:string|null;state:string|null;notes:string|null};
type Ingredient={id:string;household_id:string;business_id:string;supplier_id:string|null;name:string;category:string|null;base_unit:"G"|"ML"|"UN";purchase_quantity:number;purchase_unit:string;purchase_cost:number;cost_per_base_unit:number;stock_quantity:number;minimum_stock:number;notes:string|null};
type Recipe={id:string;household_id:string;business_id:string;name:string;category:string|null;yield_quantity:number;yield_unit:string;preparation:string|null;notes:string|null};
type RecipeItem={id:string;household_id:string;business_id:string;recipe_id:string;ingredient_id:string;quantity:number;waste_percent:number};
type Product={id:string;household_id:string;business_id:string;recipe_id:string|null;name:string;category:string|null;product_type:string;price:number;margin_percent:number;markup:number;extra_cost:number;packaging_cost:number;labor_cost:number;fee_percent:number;notes:string|null};
type Supplier={id:string;household_id:string;business_id:string;name:string;document:string|null;phone:string|null;email:string|null;address:string|null;notes:string|null};
type Production={id:string;household_id:string;business_id:string;product_id:string;quantity:number;produced_at:string;total_cost:number;notes:string|null};
type Sale={id:string;household_id:string;business_id:string;sale_date:string;customer_name:string|null;payment_method:string|null;total_amount:number;status:string;notes:string|null};
type Cash={id:string;household_id:string;business_id:string;entry_date:string;description:string;entry_type:"ENTRADA"|"SAIDA";category:string|null;amount:number;source_type:string|null;source_id:string|null;notes:string|null};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const todaySP=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());
const num=(v:string)=>{const raw=v.trim().replace(/\s/g,"");if(!raw)return 0;const normalized=raw.includes(",")?raw.replace(/\./g,"").replace(",","."):raw;return Number(normalized)||0;};
type TableApi<T>={insert:(values:Record<string,unknown>)=>Promise<T>;update:(id:string,values:Record<string,unknown>)=>Promise<T>};
const inputClass="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/10";
const btnClass="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-[10px] font-bold tracking-[0.04em] text-primary-foreground shadow-sm transition-all hover:-translate-y-0.5 hover:opacity-90 active:scale-[0.98]";
const saveBtnClass="gradient-primary label-caps inline-flex w-fit items-center justify-center rounded-lg px-3 py-1.5 text-[9px] font-semibold text-primary-foreground";
const secondaryBtnClass="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-border/70 bg-card px-4 text-[10px] font-bold tracking-[0.04em] text-foreground shadow-sm transition-all hover:border-primary/40 hover:bg-primary/5 active:scale-[0.98]";
const textareaClass=inputClass+" min-h-24 resize-none";
function Field({label,children,className=""}:{label:string;children:React.ReactNode;className?:string}){return <label className={className}><span className="label-caps text-[9px] text-muted-foreground">{label}</span><div className="mt-1">{children}</div></label>}
function FormShell({title,open,setOpen,children}:{title:string;open:boolean;setOpen:(v:boolean)=>void;children:React.ReactNode}){if(!open)return null;return <section className="rounded-2xl border border-border/70 bg-card p-5 shadow-[0_12px_40px_-30px_rgba(0,0,0,0.8)] md:p-6"><div className="mb-4"><p className="label-caps text-[9px] font-semibold tracking-[0.18em] text-primary">CADASTRO</p><h2 className="mt-1 text-base font-bold tracking-tight md:text-lg">{title}</h2></div><div className="space-y-4">{children}</div></section>}

function EmpresarialPage(){
 const [tab,setTab]=useState<Tab>(()=>{if(typeof window==="undefined")return "DASHBOARD";const raw=window.location.hash.slice(1);try{const current=decodeURIComponent(raw);if(tabs.some(t=>t.id===current))return current as Tab;const saved=localStorage.getItem("harmony:last-business-tab");if(saved&&tabs.some(t=>t.id===saved))return saved as Tab}catch{void 0}return "DASHBOARD"}),[businessId,setBusinessId]=useState<string|null>(null);
 useEffect(()=>{const syncHash=()=>{if(typeof window==="undefined")return;const raw=window.location.hash.slice(1);let hash="";try{hash=decodeURIComponent(raw)}catch{hash=raw}if(tabs.some(t=>t.id===hash)){setTab(hash as Tab);try{localStorage.setItem("harmony:last-business-tab",hash)}catch{void 0}}else{try{const saved=localStorage.getItem("harmony:last-business-tab");if(saved&&tabs.some(t=>t.id===saved))setTab(saved as Tab)}catch{void 0}}};syncHash();window.addEventListener("hashchange",syncHash);return()=>window.removeEventListener("hashchange",syncHash)},[]);
 const businesses=useHouseholdTable<Business>("businesses","*","name"),ingredients=useHouseholdTable<Ingredient>("business_ingredients","*","name"),recipes=useHouseholdTable<Recipe>("business_recipes","*","name"),recipeItems=useHouseholdTable<RecipeItem>("business_recipe_items","*","created_at"),products=useHouseholdTable<Product>("business_products","*","name"),suppliers=useHouseholdTable<Supplier>("business_suppliers","*","name"),productions=useHouseholdTable<Production>("business_productions","*","produced_at"),sales=useHouseholdTable<Sale>("business_sales","*","sale_date"),cash=useHouseholdTable<Cash>("business_cash_entries","*","entry_date");
 const business=businesses.rows.find(x=>x.id===businessId)??businesses.rows[0]??null,activeId=business?.id??null;
 const filter=<T extends {business_id:string}>(rows:T[]):T[]=>activeId?rows.filter(x=>x.business_id===activeId):[];
 const bi=filter(ingredients.rows),br=filter(recipes.rows),bri=filter(recipeItems.rows),bp=filter(products.rows),bs=filter(suppliers.rows),bprod=filter(productions.rows),bsa=filter(sales.rows),bc=filter(cash.rows);
 const stockValue=bi.reduce((s,x)=>s+Number(x.stock_quantity)*Number(x.cost_per_base_unit),0),monthKey=todaySP().slice(0,7),salesTotal=bsa.filter(x=>x.sale_date?.startsWith(monthKey)&&x.status!=="CANCELADA").reduce((s,x)=>s+Number(x.total_amount),0),cashIn=bc.filter(x=>x.entry_type==="ENTRADA").reduce((s,x)=>s+Number(x.amount),0),cashOut=bc.filter(x=>x.entry_type==="SAIDA").reduce((s,x)=>s+Number(x.amount),0);
 return <div className="space-y-5">

 {!activeId&&tab!=="EMPRESA"?<Panel><div className="py-10 text-center"><Building2 className="mx-auto mb-3 h-9 w-9 text-primary"/><p className="font-bold">CADASTRE SUA EMPRESA PRIMEIRO</p><p className="mt-1 text-sm text-muted-foreground">O módulo empresarial mantém estoque, receitas, produção e caixa separados do financeiro pessoal.</p><button className={saveBtnClass+" mt-4"} onClick={()=>setTab("EMPRESA")}><Plus className="h-4 w-4"/>CADASTRAR EMPRESA</button></div></Panel>:
 <>
 {businesses.rows.length>1&&<div className="flex items-center gap-2"><span className="label-caps text-[9px] text-muted-foreground">EMPRESA ATIVA</span><select className={inputClass+" max-w-xs"} value={activeId??""} onChange={e=>setBusinessId(e.target.value)}>{businesses.rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>}
 {tab==="DASHBOARD"&&<Dashboard ingredients={bi} recipes={br} products={bp} productions={bprod} stockValue={stockValue} salesTotal={salesTotal} cashIn={cashIn} cashOut={cashOut} salesRows={bsa} cashRows={bc} onNavigate={setTab}/>}
 {tab==="EMPRESA"&&<CompanyTab business={business} table={businesses} onSelected={setBusinessId}/>}
 {tab==="INSUMOS"&&<IngredientsTab business={business} rows={bi} table={ingredients} suppliers={bs}/>}
 {tab==="RECEITAS"&&<RecipesTab business={business} rows={br} items={bri} ingredients={bi} recipesTable={recipes} itemsTable={recipeItems}/>}
 {tab==="PRECIFICAÇÃO"&&<PricingTab business={business} products={bp} recipes={br} ingredients={bi} items={bri} table={products}/>}
 {tab==="FORNECEDORES"&&<SuppliersTab business={business} rows={bs} table={suppliers}/>}
 {tab==="PRODUÇÃO"&&<ProductionTab business={business} rows={bprod} products={bp} table={productions} ingredients={bi}/>}
 {tab==="VENDAS"&&<SalesTab business={business} rows={bsa} products={bp} table={sales}/>}
 {tab==="FINANCEIRO"&&<FinanceTab business={business} cash={bc} cashTable={cash}/>}
 </>}</div>
}

function Dashboard({ingredients,recipes,products,productions,stockValue,salesTotal,cashIn,cashOut,salesRows,cashRows,onNavigate}:{ingredients:Ingredient[];recipes:Recipe[];products:Product[];productions:Production[];stockValue:number;salesTotal:number;cashIn:number;cashOut:number;salesRows:Sale[];cashRows:Cash[];onNavigate:(tab:Tab)=>void}){
 const { profile } = useAuth();
 const [isMounted,setIsMounted]=useState(false);
 useEffect(()=>{setIsMounted(true)},[]);
 const low=ingredients.filter(x=>Number(x.stock_quantity)<=Number(x.minimum_stock));
 const missingRecipeProducts=products.filter(x=>!x.recipe_id);
 const cashBalance=cashIn-cashOut;
 const now=new Date();
 const monthName=now.toLocaleDateString("pt-BR",{month:"long",year:"numeric"}).toUpperCase();
 const greeting=now.getHours()<12?"BOM DIA":now.getHours()<18?"BOA TARDE":"BOA NOITE";
 const setupSteps=[{done:ingredients.length>0,label:"Cadastrar insumos",tab:"INSUMOS" as Tab},{done:recipes.length>0,label:"Criar fichas técnicas",tab:"RECEITAS" as Tab},{done:products.length>0,label:"Cadastrar produtos",tab:"PRECIFICAÇÃO" as Tab},{done:products.length>0&&ingredients.length>0,label:"Preparar operação",tab:"PRODUÇÃO" as Tab}];
 const completed=setupSteps.filter(x=>x.done).length;
 const monthlyEvolution=useMemo(()=>Array.from({length:6},(_,idx)=>{const d=new Date(now.getFullYear(),now.getMonth()-5+idx,1);const key=d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0");return{mes:d.toLocaleDateString("pt-BR",{month:"short"}).replace(".","").toUpperCase(),vendas:salesRows.filter(x=>x.sale_date?.startsWith(key)&&x.status!=="CANCELADA").reduce((s,x)=>s+Number(x.total_amount),0),entradas:cashRows.filter(x=>x.entry_date?.startsWith(key)&&x.entry_type==="ENTRADA").reduce((s,x)=>s+Number(x.amount),0),saidas:cashRows.filter(x=>x.entry_date?.startsWith(key)&&x.entry_type==="SAIDA").reduce((s,x)=>s+Number(x.amount),0)}}),[salesRows,cashRows]);
 const productDistribution=useMemo(()=>products.slice().sort((a,b)=>Number(b.price)-Number(a.price)).slice(0,5).map(p=>({name:p.name,value:Number(p.price)||0})),[products]);
 const PIE_COLORS=["var(--orange-primary)","var(--orange-light)","var(--graphite-light)","var(--muted-foreground)","var(--danger)"];
 return <div className="space-y-5">
  <PageHeader title={greeting+", "+(profile?.name?.split(" ")[0]?.toUpperCase()||"")} subtitle={"Veja como está a operação de "+monthName.toLowerCase()+"."} action={<Tag tone="primary">{monthName}</Tag>}/>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="VENDAS DO MÊS" value={money(salesTotal)} delta="Vendas registradas" tone="success" icon={<ShoppingCart className="h-4 w-4"/>}/><StatCard label="CAIXA" value={money(cashBalance)} delta="Saldo operacional" tone={cashBalance>=0?"primary":"danger"} icon={<Wallet className="h-4 w-4"/>}/><StatCard label="ESTOQUE" value={money(stockValue)} delta={ingredients.length+" insumos"} tone="info" icon={<Package className="h-4 w-4"/>}/><StatCard label="ESTOQUE EM ATENÇÃO" value={String(low.length)} delta={low.length?"Requer ação":"Tudo dentro do mínimo"} tone={low.length?"danger":"success"} icon={<AlertTriangle className="h-4 w-4"/>}/></div>
  <Panel className="border-warning/50"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-warning/15 text-warning"><AlertTriangle className="h-5 w-5"/></span><div><h2 className="label-caps text-sm">AÇÃO NECESSÁRIA</h2><p className="text-xs text-muted-foreground">{low.length?low.length+" insumo(s) abaixo do estoque mínimo.":"Nenhum alerta crítico de estoque."}</p></div></div><button type="button" onClick={()=>onNavigate("INSUMOS")} className="label-caps rounded-xl border border-primary/60 px-3 py-2 text-[11px] text-primary">VER ESTOQUE</button></div></Panel>
  <div className="grid gap-4 lg:grid-cols-3"><Panel title="EVOLUÇÃO RECENTE" className="lg:col-span-2"><div className="h-64">{isMounted&&<ResponsiveContainer width="100%" height="100%"><AreaChart data={monthlyEvolution}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="mes" stroke="var(--muted-foreground)" fontSize={11} tickLine={false}/><YAxis stroke="var(--muted-foreground)" fontSize={11} tickLine={false} width={48}/><Tooltip formatter={(v:number)=>money(v)}/><Area type="monotone" dataKey="vendas" stroke="var(--orange-primary)" fill="var(--orange-primary)" fillOpacity={0.15}/><Area type="monotone" dataKey="entradas" stroke="var(--success)" fill="transparent"/><Area type="monotone" dataKey="saidas" stroke="var(--danger)" fill="transparent"/></AreaChart></ResponsiveContainer>}</div></Panel><Panel title="PRODUTOS"><div className="h-64">{isMounted&&(productDistribution.length?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={productDistribution} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85} paddingAngle={3} stroke="none">{productDistribution.map((entry,index)=><Cell key={entry.name} fill={PIE_COLORS[index%5]}/>)}</Pie><Legend wrapperStyle={{fontSize:10}}/><Tooltip formatter={(v:number)=>money(v)}/></PieChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center text-sm text-muted-foreground">Cadastre produtos para visualizar.</div>)}</div></Panel></div>
  <div className="grid gap-4 lg:grid-cols-2"><Panel title="PRÓXIMOS PASSOS"><div className="space-y-2">{setupSteps.map(step=><button key={step.label} type="button" onClick={()=>onNavigate(step.tab)} className="flex w-full items-center justify-between rounded-xl border border-border bg-secondary/20 p-3 text-left transition hover:border-primary/40 hover:bg-primary/5"><span className="flex items-center gap-3"><span className={"flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-bold "+(step.done?"bg-success/10 text-success":"bg-primary/10 text-primary")}>{step.done?"✓":"→"}</span><span className="text-sm font-semibold">{step.label}</span></span><span className="text-[9px] font-bold text-muted-foreground">{step.done?"CONCLUÍDO":"CONFIGURAR"}</span></button>)}</div><div className="mt-3 rounded-xl bg-secondary/50 p-3 text-[10px] text-muted-foreground"><b className="text-foreground">{completed}/{setupSteps.length}</b> etapas básicas configuradas.</div></Panel><Panel title="OPERAÇÃO"><div className="grid grid-cols-2 gap-3 text-center">{[["INSUMOS",ingredients.length,"INSUMOS"],["RECEITAS",recipes.length,"RECEITAS"],["PRODUTOS",products.length,"PRECIFICAÇÃO"],["PRODUÇÕES",productions.length,"PRODUÇÃO"]].map(([label,value,target])=><button key={String(label)} type="button" onClick={()=>onNavigate(target as Tab)} className="rounded-xl p-2 hover:bg-secondary/60"><p className="text-2xl font-bold">{value}</p><p className="label-caps text-[9px] text-muted-foreground">{label}</p></button>)}</div></Panel></div>
  <div className="grid gap-4 lg:grid-cols-2"><Panel title="ESTOQUE — AÇÃO NECESSÁRIA">{low.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Nenhum insumo abaixo do mínimo.</p>:<div className="space-y-2">{low.slice(0,6).map(x=><button key={x.id} type="button" onClick={()=>onNavigate("INSUMOS")} className="flex w-full items-center justify-between rounded-xl border border-warning/30 bg-warning/5 p-3 text-left"><span><span className="block text-sm font-semibold">{x.name}</span><span className="text-[10px] text-muted-foreground">MÍNIMO {x.minimum_stock} {x.base_unit}</span></span><span className="flex items-center gap-2 text-warning"><span className="text-xs font-bold">{x.stock_quantity} {x.base_unit}</span><AlertTriangle className="h-4 w-4"/></span></button>)}</div>}</Panel><Panel title="CADASTRO INTELIGENTE">{missingRecipeProducts.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Todos os produtos estão vinculados a uma ficha técnica ou ainda não há produtos.</p>:<div className="space-y-2"><p className="text-xs text-muted-foreground">Produtos sem ficha técnica não calculam custo e consumo de estoque corretamente.</p>{missingRecipeProducts.slice(0,6).map(x=><button key={x.id} type="button" onClick={()=>onNavigate("PRECIFICAÇÃO")} className="flex w-full items-center justify-between rounded-xl border p-3 text-left"><span className="text-sm font-semibold">{x.name}</span><span className="text-[9px] font-bold text-primary">REVISAR <ArrowRight className="ml-1 inline h-3 w-3"/></span></button>)}</div>}</Panel></div>
 </div>;
}
function CompanyTab({business,table,onSelected}:{business:Business|null;table:TableApi<Business>;onSelected:(id:string)=>void}){
 const [open,setOpen]=useState(false),[more,setMore]=useState(false),[name,setName]=useState(business?.name??""),[legal,setLegal]=useState(business?.legal_name??""),[document,setDocument]=useState(business?.document??""),[taxRegime,setTaxRegime]=useState(business?.tax_regime??""),[phone,setPhone]=useState(business?.phone??""),[email,setEmail]=useState(business?.email??""),[address,setAddress]=useState(business?.address??""),[city,setCity]=useState(business?.city??""),[state,setState]=useState(business?.state??""),[notes,setNotes]=useState(business?.notes??"");
 async function save(){if(!name.trim())return toast.error("INFORME O NOME DA EMPRESA");try{const row=business?await table.update(business.id,{name:name.trim().toUpperCase(),legal_name:legal||null,document:document||null,tax_regime:taxRegime||null,phone:phone||null,email:email||null,address:address||null,city:city||null,state:state||null,notes:notes||null}):await table.insert({name:name.trim().toUpperCase(),legal_name:legal||null,document:document||null,tax_regime:taxRegime||null,phone:phone||null,email:email||null,address:address||null,city:city||null,state:state||null,notes:notes||null});onSelected(row.id);setOpen(false);toast.success("EMPRESA SALVA")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO SALVAR EMPRESA")}}
 return <div className="space-y-4"><PageHeader title="EMPRESA" subtitle="DADOS CADASTRAIS E INFORMAÇÕES DA EMPRESA." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"EDITAR EMPRESA"}</button>}/>{open&&<Panel title="EMPRESA"><div className="grid gap-4 md:grid-cols-2">
  <Field label="NOME DA EMPRESA *"><input type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="NOME DA EMPRESA" className={inputClass}/></Field><Field label="CNPJ / CPF"><input value={document} onChange={e=>setDocument(e.target.value)} placeholder="CNPJ / CPF" className={inputClass}/></Field><Field label="TELEFONE"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="TELEFONE" className={inputClass}/></Field><Field label="E-MAIL"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-MAIL" className={inputClass}/></Field>
 </div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><button onClick={()=>void save()} className={saveBtnClass+" mt-4"}><Save className="h-4 w-4"/>SALVAR EMPRESA</button><button type="button" onClick={()=>setMore(v=>!v)} className={secondaryBtnClass+" w-full sm:w-auto"}>{more?"OCULTAR DADOS EXTRAS":"ADICIONAR MAIS INFORMAÇÕES"}</button></div>
 {more&&<div className="mt-5 border-t border-border/60 pt-5"><div className="grid gap-4 md:grid-cols-2"><Field label="RAZÃO SOCIAL"><input value={legal} onChange={e=>setLegal(e.target.value)} placeholder="RAZÃO SOCIAL" className={inputClass}/></Field><Field label="REGIME TRIBUTÁRIO"><select className={inputClass} value={taxRegime} onChange={e=>setTaxRegime(e.target.value)}><option value="">SELECIONE</option><option>SIMPLES NACIONAL</option><option>LUCRO PRESUMIDO</option><option>LUCRO REAL</option><option>MEI</option><option>OUTRO</option></select></Field><Field label="ENDEREÇO"><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="ENDEREÇO" className={inputClass}/></Field><Field label="CIDADE"><input value={city} onChange={e=>setCity(e.target.value)} placeholder="CIDADE" className={inputClass}/></Field><Field label="UF"><input maxLength={2} value={state} onChange={e=>setState(e.target.value.toUpperCase())} placeholder="UF" className={inputClass}/></Field><Field label="OBSERVAÇÕES" className="md:col-span-2"><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="OBSERVAÇÕES" className={textareaClass} rows={3}/></Field></div><button onClick={()=>void save()} className={saveBtnClass+" mt-4"}><Save className="h-4 w-4"/>SALVAR ALTERAÇÕES</button></div>}</Panel>}
 {business&&!open&&<Panel title="DADOS DA EMPRESA"><div className="grid gap-4 sm:grid-cols-2"><div><p className="label-caps text-[9px] text-muted-foreground">EMPRESA</p><p className="mt-1 text-sm font-semibold">{business.name}</p></div><div><p className="label-caps text-[9px] text-muted-foreground">DOCUMENTO</p><p className="mt-1 text-sm">{business.document??"—"}</p></div><div><p className="label-caps text-[9px] text-muted-foreground">REGIME</p><p className="mt-1 text-sm">{business.tax_regime??"—"}</p></div><div><p className="label-caps text-[9px] text-muted-foreground">CONTATO</p><p className="mt-1 text-sm">{business.email??business.phone??"—"}</p></div></div><button type="button" className={secondaryBtnClass+" mt-5"} onClick={()=>{setName(business.name);setLegal(business.legal_name??"");setDocument(business.document??"");setTaxRegime(business.tax_regime??"");setPhone(business.phone??"");setEmail(business.email??"");setAddress(business.address??"");setCity(business.city??"");setState(business.state??"");setNotes(business.notes??"");setOpen(true)}}><Building2 className="h-4 w-4"/>EDITAR EMPRESA</button></Panel>}</div>
}function IngredientsTab({business,rows,table,suppliers}:{business:Business|null;rows:Ingredient[];table:TableApi<Ingredient>;suppliers:Supplier[]}){
 const [open,setOpen]=useState(false),[name,setName]=useState(""),[unit,setUnit]=useState<"G"|"ML"|"UN">("G"),[purchaseUnit,setPurchaseUnit]=useState("KG"),[qty,setQty]=useState(""),[cost,setCost]=useState(""),[stock,setStock]=useState(""),[min,setMin]=useState(""),[supplier,setSupplier]=useState("");
 async function save(){if(!business||!name.trim())return toast.error("PREENCHA O INSUMO");try{await table.insert({business_id:business.id,name:name.trim().toUpperCase(),base_unit:unit,purchase_unit:purchaseUnit,purchase_quantity:num(qty),purchase_cost:num(cost),stock_quantity:num(stock),minimum_stock:num(min),supplier_id:supplier||null});setOpen(false);setName("");setQty("");setCost("");setStock("");setMin("");setSupplier("");toast.success("INSUMO SALVO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO")}}
 return <div className="space-y-4"><PageHeader title="INSUMOS" subtitle="CUSTO AUTOMÁTICO POR GRAMA, ML OU UNIDADE E ESTOQUE." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"NOVO INSUMO"}</button>}/><FormShell title="NOVO INSUMO" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-4"><Field label="NOME"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="UNIDADE BASE"><select className={inputClass} value={unit} onChange={e=>setUnit(e.target.value as Ingredient["base_unit"])}><option>G</option><option>ML</option><option>UN</option></select></Field><Field label="UNIDADE DE COMPRA"><select className={inputClass} value={purchaseUnit} onChange={e=>setPurchaseUnit(e.target.value)}>{["G","KG","ML","L","UN"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="QUANTIDADE COMPRADA"><input className={inputClass} value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="VALOR PAGO"><input className={inputClass} value={cost} onChange={e=>setCost(e.target.value)}/></Field><Field label="ESTOQUE INICIAL"><input className={inputClass} value={stock} onChange={e=>setStock(e.target.value)}/></Field><Field label="ESTOQUE MÍNIMO"><input className={inputClass} value={min} onChange={e=>setMin(e.target.value)}/></Field><Field label="FORNECEDOR"><select className={inputClass} value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">NÃO INFORMADO</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><Save className="h-4 w-4"/>SALVAR INSUMO</button></FormShell><Panel title="ESTOQUE DE INSUMOS"><div className="divide-y divide-border">{rows.map(x=><div key={x.id} className="flex items-center justify-between py-3"><div><p className="font-semibold">{x.name}</p><p className="text-[10px] text-muted-foreground">CUSTO {money(Number(x.cost_per_base_unit))}/{x.base_unit}</p></div><div className="text-right"><p className="font-bold">{x.stock_quantity} {x.base_unit}</p>{Number(x.stock_quantity)<=Number(x.minimum_stock)&&<Tag tone="warning">REPOR</Tag>}</div></div>)}</div></Panel></div>
}

function RecipesTab({business,rows,items,ingredients,recipesTable,itemsTable}:{business:Business|null;rows:Recipe[];items:RecipeItem[];ingredients:Ingredient[];recipesTable:TableApi<Recipe>;itemsTable:TableApi<RecipeItem>}){
 const [open,setOpen]=useState(false),[name,setName]=useState(""),[yieldQty,setYieldQty]=useState("1"),[yieldUnit,setYieldUnit]=useState("UN"),[ingredientId,setIngredientId]=useState(""),[ingredientQty,setIngredientQty]=useState(""),[waste,setWaste]=useState("0"),[draft,setDraft]=useState<{ingredient_id:string;quantity:string;waste:string}[]>([]);
 const addItem=()=>{if(ingredientId&&num(ingredientQty)>0)setDraft([...draft,{ingredient_id:ingredientId,quantity:ingredientQty,waste}]);setIngredientId("");setIngredientQty("");setWaste("0")};
 async function save(){if(!business||!name.trim()||!draft.length)return toast.error("INFORME A RECEITA E OS INGREDIENTES");try{const r=await recipesTable.insert({business_id:business.id,name:name.trim().toUpperCase(),yield_quantity:num(yieldQty)||1,yield_unit:yieldUnit});for(const x of draft)await itemsTable.insert({business_id:business.id,recipe_id:r.id,ingredient_id:x.ingredient_id,quantity:num(x.quantity),waste_percent:num(x.waste)});setOpen(false);setDraft([]);setName("");toast.success("FICHA TÉCNICA SALVA")}catch(e){toast.error(e instanceof Error?e.message:"ERRO")}}
 const cost=(r:Recipe)=>items.filter(x=>x.recipe_id===r.id).reduce((s,x)=>s+Number(x.quantity)*(1+Number(x.waste_percent)/100)*Number(ingredients.find(i=>i.id===x.ingredient_id)?.cost_per_base_unit||0),0);
 return <div className="space-y-4"><PageHeader title="RECEITAS" subtitle="FICHAS TÉCNICAS: INGREDIENTES, RENDIMENTO, PERDAS E CUSTO." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"NOVA RECEITA"}</button>}/><FormShell title="NOVA RECEITA / FICHA TÉCNICA" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-3"><Field label="NOME"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="RENDIMENTO"><input className={inputClass} value={yieldQty} onChange={e=>setYieldQty(e.target.value)}/></Field><Field label="UNIDADE"><input className={inputClass} value={yieldUnit} onChange={e=>setYieldUnit(e.target.value.toUpperCase())}/></Field></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Field label="INGREDIENTE"><select className={inputClass} value={ingredientId} onChange={e=>setIngredientId(e.target.value)}><option value="">SELECIONE</option>{ingredients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="QTD. BASE"><input className={inputClass} value={ingredientQty} onChange={e=>setIngredientQty(e.target.value)}/></Field><Field label="PERDA %"><input className={inputClass} value={waste} onChange={e=>setWaste(e.target.value)}/></Field><button className={btnClass+" self-end"} onClick={addItem}><Plus className="h-4 w-4"/>ADICIONAR</button></div><div className="mt-3 space-y-2">{draft.map((x,i)=><div key={i} className="flex justify-between rounded-xl border p-3 text-xs"><span>{ingredients.find(y=>y.id===x.ingredient_id)?.name}</span><span>{x.quantity} + {x.waste}%</span></div>)}</div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><Save className="h-4 w-4"/>SALVAR FICHA</button></FormShell><div className="grid gap-3 md:grid-cols-2">{rows.map(r=><Panel key={r.id}><div className="flex justify-between"><div><p className="font-bold">{r.name}</p><p className="text-[10px] text-muted-foreground">RENDE {r.yield_quantity} {r.yield_unit}</p></div><Tag tone="primary">{money(cost(r))} CUSTO</Tag></div><div className="mt-3 space-y-1">{items.filter(x=>x.recipe_id===r.id).map(x=><div key={x.id} className="flex justify-between text-xs text-muted-foreground"><span>{ingredients.find(y=>y.id===x.ingredient_id)?.name}</span><span>{x.quantity} {ingredients.find(y=>y.id===x.ingredient_id)?.base_unit}</span></div>)}</div></Panel>)}</div></div>
}

function PricingTab({business,products,recipes,ingredients,items,table}:{business:Business|null;products:Product[];recipes:Recipe[];ingredients:Ingredient[];items:RecipeItem[];table:TableApi<Product>}){
 const [open,setOpen]=useState(false),[name,setName]=useState(""),[productType,setProductType]=useState<Product["product_type"]>("PRODUTO"),[recipeId,setRecipeId]=useState(""),[margin,setMargin]=useState("50"),[pack,setPack]=useState("0"),[labor,setLabor]=useState("0"),[extra,setExtra]=useState("0"),[fee,setFee]=useState("0"),[price,setPrice]=useState("0");
 const recipeCostTotal=useMemo(()=>items.filter(x=>x.recipe_id===recipeId).reduce((s,x)=>s+Number(x.quantity)*(1+Number(x.waste_percent)/100)*Number(ingredients.find(i=>i.id===x.ingredient_id)?.cost_per_base_unit||0),0),[recipeId,items,ingredients]);
 const selectedRecipe=recipes.find(x=>x.id===recipeId); const yieldQuantity=Math.max(Number(selectedRecipe?.yield_quantity)||1,1); const recipeCost=recipeCostTotal/yieldQuantity;
 const totalCost=recipeCost+num(pack)+num(labor)+num(extra),suggested=totalCost>0?totalCost*(1+num(margin)/100)/(1-num(fee)/100):0;
 async function save(){if(!business||!name.trim())return;try{await table.insert({business_id:business.id,name:name.trim().toUpperCase(),product_type:productType,recipe_id:productType==="SERVICO"?null:(recipeId||null),price:num(price)||suggested,margin_percent:num(margin),markup:totalCost?suggested/totalCost:1,packaging_cost:num(pack),labor_cost:num(labor),extra_cost:num(extra),fee_percent:num(fee)});setOpen(false);toast.success("PRODUTO PRECIFICADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO")}}
 return <div className="space-y-4"><PageHeader title="PRECIFICAÇÃO" subtitle="CUSTO TOTAL, MARGEM, MARKUP, TAXAS, PREÇO MÍNIMO E SUGERIDO." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"NOVO PRODUTO"}</button>}/><FormShell title="PRECIFICAR PRODUTO / SERVIÇO" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-3"><Field label="NOME"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)} placeholder="NOME DO ITEM"/></Field><Field label="TIPO"><select className={inputClass} value={productType} onChange={e=>setProductType(e.target.value as Product["product_type"])}><option value="PRODUTO">PRODUTO</option><option value="SERVICO">SERVIÇO</option></select></Field><Field label="RECEITA"><select className={inputClass} value={recipeId} disabled={productType==="SERVICO"} onChange={e=>setRecipeId(e.target.value)}><option value="">SEM RECEITA</option>{recipes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="MARGEM %"><input className={inputClass} value={margin} onChange={e=>setMargin(e.target.value)}/></Field><Field label="EMBALAGEM"><input className={inputClass} value={pack} onChange={e=>setPack(e.target.value)}/></Field><Field label="MÃO DE OBRA"><input className={inputClass} value={labor} onChange={e=>setLabor(e.target.value)}/></Field><Field label="OUTROS CUSTOS"><input className={inputClass} value={extra} onChange={e=>setExtra(e.target.value)}/></Field><Field label="TAXA %"><input className={inputClass} value={fee} onChange={e=>setFee(e.target.value)}/></Field><Field label="PREÇO MANUAL"><input className={inputClass} value={price} onChange={e=>setPrice(e.target.value)}/></Field></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><StatCard label="CUSTO TOTAL" value={money(totalCost)} tone="info"/><StatCard label="PREÇO SUGERIDO" value={money(suggested)} tone="success"/><StatCard label="MARKUP" value={totalCost?(suggested/totalCost).toFixed(2)+"x":"—"} tone="primary"/></div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><Save className="h-4 w-4"/>SALVAR PRODUTO</button></FormShell><Panel title="PRODUTOS / SERVIÇOS"><div className="grid gap-3 md:grid-cols-2">{products.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="flex justify-between"><p className="font-bold">{p.name}</p><p className="font-bold text-success">{money(Number(p.price))}</p></div><p className="mt-1 text-[10px] text-muted-foreground">{p.product_type==="SERVICO"?"SERVIÇO":"PRODUTO"} · MARKUP {Number(p.markup).toFixed(2)}x · MARGEM {p.margin_percent}%</p></div>)}</div></Panel></div>
}

function SuppliersTab({business,rows,table}:{business:Business|null;rows:Supplier[];table:TableApi<Supplier>}){
 const [open,setOpen]=useState(false),[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState("");
 async function save(){if(!business||!name.trim())return;try{await table.insert({business_id:business.id,name:name.trim().toUpperCase(),phone:phone||null,email:email||null});setOpen(false);setName("");setPhone("");setEmail("");toast.success("FORNECEDOR SALVO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO")}}
 return <div className="space-y-4"><PageHeader title="FORNECEDORES" subtitle="FORNECEDORES DOS INSUMOS E COMPRAS." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"NOVO FORNECEDOR"}</button>}/><FormShell title="NOVO FORNECEDOR" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-3"><Field label="NOME"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="TELEFONE"><input className={inputClass} value={phone} onChange={e=>setPhone(e.target.value)}/></Field><Field label="E-MAIL"><input className={inputClass} value={email} onChange={e=>setEmail(e.target.value)}/></Field></div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><Save className="h-4 w-4"/>SALVAR</button></FormShell><Panel title="FORNECEDORES"><div className="divide-y divide-border">{rows.map(x=><div key={x.id} className="flex justify-between py-3"><div><p className="font-semibold">{x.name}</p><p className="text-[10px] text-muted-foreground">{x.phone??x.email??"SEM CONTATO"}</p></div></div>)}</div></Panel></div>
}

function ProductionTab({business,rows,products,table,ingredients}:{business:Business|null;rows:Production[];products:Product[];table:TableApi<Production>;ingredients:Ingredient[]}){
 const [open,setOpen]=useState(false),[product,setProduct]=useState(""),[qty,setQty]=useState("1"),[date,setDate]=useState(new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date()));
 async function save(){if(!business||!product||num(qty)<=0)return;try{await table.insert({business_id:business.id,product_id:product,quantity:num(qty),produced_at:date});setOpen(false);toast.success("PRODUÇÃO REGISTRADA — INGREDIENTES BAIXADOS AUTOMATICAMENTE")}catch(e){toast.error(e instanceof Error?e.message:"ERRO: ESTOQUE INSUFICIENTE OU RECEITA SEM INGREDIENTES")}}
 return <div className="space-y-4"><PageHeader title="PRODUÇÃO / ESTOQUE" subtitle="A PRODUÇÃO CONSOME AUTOMATICAMENTE OS INGREDIENTES DA FICHA TÉCNICA." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"REGISTRAR PRODUÇÃO"}</button>}/><FormShell title="REGISTRAR PRODUÇÃO" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-3"><Field label="PRODUTO"><select className={inputClass} value={product} onChange={e=>setProduct(e.target.value)}><option value="">SELECIONE</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="QUANTIDADE"><input className={inputClass} value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="DATA"><input type="date" className={inputClass} value={date} onChange={e=>setDate(e.target.value)}/></Field></div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><Factory className="h-4 w-4"/>CONFIRMAR PRODUÇÃO</button></FormShell><div className="grid gap-4 lg:grid-cols-2"><Panel title="PRODUÇÕES"><div className="divide-y divide-border">{rows.slice(0,20).map(x=><div key={x.id} className="flex justify-between py-3"><div><p className="font-semibold">{products.find(p=>p.id===x.product_id)?.name??"PRODUTO"}</p><p className="text-[10px] text-muted-foreground">{x.produced_at}</p></div><div className="text-right"><p>{x.quantity} un.</p><p className="text-[10px] text-muted-foreground">CUSTO {money(Number(x.total_cost))}</p></div></div>)}</div></Panel><Panel title="ESTOQUE ATUAL"><div className="divide-y divide-border">{ingredients.map(x=><div key={x.id} className="flex justify-between py-2 text-sm"><span>{x.name}</span><span>{x.stock_quantity} {x.base_unit}</span></div>)}</div></Panel></div></div>
}

function SalesTab({business,rows,products,table}:{business:Business|null;rows:Sale[];products:Product[];table:TableApi<Sale>}){
 const [open,setOpen]=useState(false),[product,setProduct]=useState(""),[qty,setQty]=useState("1"),[price,setPrice]=useState("0"),[customer,setCustomer]=useState(""),[paymentMethod,setPaymentMethod]=useState("PIX"),[date,setDate]=useState(todaySP());
 async function save(){if(!business||!product||num(qty)<=0)return;try{const total=num(price)*num(qty);const sale=await table.insert({business_id:business.id,sale_date:date,customer_name:customer||null,payment_method:paymentMethod,total_amount:total,status:"RECEBIDA"});const {error}=await supabase.from("business_sale_items").insert({household_id:sale.household_id,business_id:business.id,sale_id:sale.id,product_id:product,quantity:num(qty),unit_price:num(price)});if(error)throw error;setOpen(false);toast.success("VENDA REGISTRADA")}catch(e){toast.error(e instanceof Error?e.message:"ERRO")}}
 return <div className="space-y-4"><PageHeader title="VENDAS" subtitle="PRODUTO, QUANTIDADE, PREÇO E RECEITA GERADA." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"NOVA VENDA"}</button>}/><FormShell title="NOVA VENDA" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-4"><Field label="PRODUTO"><select className={inputClass} value={product} onChange={e=>{setProduct(e.target.value);const p=products.find(x=>x.id===e.target.value);if(p)setPrice(String(p.price))}}><option value="">SELECIONE</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="QUANTIDADE"><input className={inputClass} value={qty} onChange={e=>setQty(e.target.value)}/></Field><Field label="PREÇO UNITÁRIO"><input className={inputClass} value={price} onChange={e=>setPrice(e.target.value)}/></Field><Field label="FORMA DE PAGAMENTO"><select className={inputClass} value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option>PIX</option><option>CARTÃO</option><option>DINHEIRO</option><option>TRANSFERÊNCIA</option><option>BOLETO</option><option>OUTRO</option></select></Field><Field label="CLIENTE"><input className={inputClass} value={customer} onChange={e=>setCustomer(e.target.value)}/></Field></div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><ShoppingCart className="h-4 w-4"/>REGISTRAR VENDA</button></FormShell><Panel title="VENDAS"><div className="divide-y divide-border">{rows.map(x=><div key={x.id} className="flex justify-between py-3"><div><p className="font-semibold">{x.customer_name??"VENDA"}</p><p className="text-[10px] text-muted-foreground">{x.sale_date} · {x.status}</p></div><p className="font-bold text-success">{money(Number(x.total_amount))}</p></div>)}</div></Panel></div>
}

function FinanceTab({business,cash,cashTable}:{business:Business|null;cash:Cash[];cashTable:TableApi<Cash>}){
 const [open,setOpen]=useState(false),[type,setType]=useState<"ENTRADA"|"SAIDA">("ENTRADA"),[desc,setDesc]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(todaySP());
 const income=cash.filter(x=>x.entry_type==="ENTRADA").reduce((s,x)=>s+Number(x.amount),0),expense=cash.filter(x=>x.entry_type==="SAIDA").reduce((s,x)=>s+Number(x.amount),0);
 async function save(){if(!business||!desc.trim()||num(amount)<=0)return;try{await cashTable.insert({business_id:business.id,entry_date:date,description:desc.trim().toUpperCase(),entry_type:type,amount:num(amount)});setOpen(false);setDesc("");setAmount("");toast.success("LANÇAMENTO EMPRESARIAL SALVO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO")}}
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><StatCard label="ENTRADAS" value={money(income)} tone="success"/><StatCard label="SAÍDAS" value={money(expense)} tone="danger"/><StatCard label="SALDO" value={money(income-expense)} tone="primary"/></div><PageHeader title="FINANCEIRO EMPRESARIAL" subtitle="CAIXA EMPRESARIAL SEPARADO DO FINANCEIRO PESSOAL." action={<button className={btnClass} onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>{open?"FECHAR FORMULÁRIO":"NOVO LANÇAMENTO"}</button>}/><FormShell title="NOVO LANÇAMENTO DE CAIXA" open={open} setOpen={setOpen}><div className="grid gap-3 md:grid-cols-4"><Field label="TIPO"><select className={inputClass} value={type} onChange={e=>setType(e.target.value as "ENTRADA"|"SAIDA")}><option>ENTRADA</option><option>SAIDA</option></select></Field><Field label="DESCRIÇÃO"><input className={inputClass} value={desc} onChange={e=>setDesc(e.target.value)}/></Field><Field label="VALOR"><input className={inputClass} value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="DATA"><input type="date" className={inputClass} value={date} onChange={e=>setDate(e.target.value)}/></Field></div><button className={saveBtnClass+" mt-4"} onClick={()=>void save()}><Save className="h-4 w-4"/>SALVAR</button></FormShell><Panel title="FLUXO DE CAIXA"><div className="divide-y divide-border">{cash.slice(0,30).map(x=><div key={x.id} className="flex justify-between py-3"><div><p className="font-semibold">{x.description}</p><p className="text-[10px] text-muted-foreground">{x.entry_date}</p></div><p className={x.entry_type==="ENTRADA"?"font-bold text-success":"font-bold text-danger"}>{x.entry_type==="ENTRADA"?"+":"-"}{money(Number(x.amount))}</p></div>)}</div></Panel></div>
}
