import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Check, ChevronDown, Flame, Pencil, Plus, Trash2, X } from "lucide-react";
import { PageHeader, Panel } from "@/components/ui-kit";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { useAuth } from "@/hooks/use-auth";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export const Route = createFileRoute("/habitos")({ head: () => ({ meta: [{ title: "HÁBITOS — MULTICAP" }] }), component: HabitsPage });

type Habit={id:string;household_id:string;user_id:string;title:string;frequency:string;shift:string|null;privacy:string|null;created_at:string};
type HabitLog={id:string;household_id:string;habit_id:string;user_id:string;date:string;created_at:string};
const accents=["orange","blue","purple","yellow","green","red"] as const;
const accentClasses={orange:"border-orange-500/30 bg-orange-500/5 text-orange-400",blue:"border-blue-500/30 bg-blue-500/5 text-blue-400",purple:"border-purple-500/30 bg-purple-500/5 text-purple-400",yellow:"border-yellow-500/30 bg-yellow-500/5 text-yellow-400",green:"border-emerald-500/30 bg-emerald-500/5 text-emerald-400",red:"border-red-500/30 bg-red-500/5 text-red-400"};
const iconByTitle=(title:string)=>{const t=title.toLowerCase();if(t.includes("água"))return "💧";if(t.includes("academ")||t.includes("trein")||t.includes("exerc"))return "🏋️";if(t.includes("ler")||t.includes("livro")||t.includes("estud"))return "📖";if(t.includes("dorm")||t.includes("sono"))return "🛏️";if(t.includes("medit"))return "🧘";if(t.includes("finan"))return "💳";if(t.includes("banho"))return "🚿";return "✓"};
const localDate=()=>{const d=new Date();const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)};
function HabitsPage(){
 const {user}=useAuth();
 const habits=useHouseholdTable<Habit>("habits","*","created_at");
 const logs=useHouseholdTable<HabitLog>("habit_logs","*","date");
 const [tab,setTab]=useState<"MEUS HÁBITOS"|"HÁBITOS DE PARCEIRO">("MEUS HÁBITOS");
 const [title,setTitle]=useState("");const [frequency,setFrequency]=useState("daily");const [privacy,setPrivacy]=useState("private");const [showForm,setShowForm]=useState(true);
 const [editing,setEditing]=useState<Habit|null>(null);const [editTitle,setEditTitle]=useState("");const [editFrequency,setEditFrequency]=useState("daily");const [editPrivacy,setEditPrivacy]=useState("private");
 const today=localDate();
 const list=habits.rows.filter(h=>tab==="MEUS HÁBITOS"?h.user_id===user?.id:h.user_id!==user?.id);
 const myLogs=logs.rows.filter(l=>l.user_id===user?.id);
 const isDone=(habitId:string,date=today)=>myLogs.some(l=>l.habit_id===habitId&&l.date===date);
 const streak=(habitId:string)=>{let n=0;const d=new Date(`${today}T12:00:00`);while(myLogs.some(l=>l.habit_id===habitId&&l.date===d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n};
 const todayDone=list.filter(h=>isDone(h.id)).length; const total=list.length; const progress=total?Math.round(todayDone/total*100):0;
 const week=["D","S","T","Q","Q","S","S"]; const currentDay=new Date(`${today}T12:00:00`).getDay();
 const labelFrequency=(f:string)=>f==="weekly"?"Semanal":f==="monthly"?"Mensal":"Diário";
 const greeting=useMemo(()=>{const hour=new Date().getHours();return hour<12?"Bom dia":hour<18?"Boa tarde":"Boa noite"},[]);
 async function add(){const name=title.trim();if(!name)return toast.error("INFORME O NOME DO HÁBITO");if(!user?.id||!habits.householdId)return toast.error("SUA CONTA AINDA NÃO ESTÁ VINCULADA A UMA CASA");try{await habits.insert({user_id:user.id,title:name.toUpperCase(),frequency,privacy,shift:null});setTitle("");toast.success("HÁBITO ADICIONADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ADICIONAR O HÁBITO")}}
 function startEdit(h:Habit){setEditing(h);setEditTitle(h.title);setEditFrequency(h.frequency);setEditPrivacy(h.privacy??"private")}
 async function saveEdit(){if(!editing||!editTitle.trim())return toast.error("INFORME O NOME DO HÁBITO");try{await habits.update(editing.id,{title:editTitle.trim().toUpperCase(),frequency:editFrequency,privacy:editPrivacy});setEditing(null);toast.success("HÁBITO ATUALIZADO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO ATUALIZAR")}}
 async function remove(id:string){if(!window.confirm("Excluir este hábito e seu histórico?"))return;try{await habits.remove(id);toast.success("HÁBITO EXCLUÍDO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO EXCLUIR")}}
 async function toggle(habitId:string){if(!user?.id||!logs.householdId)return;const existing=myLogs.find(l=>l.habit_id===habitId&&l.date===today);try{if(existing)await logs.remove(existing.id);else await logs.insert({habit_id:habitId,user_id:user.id,date:today});toast.success(existing?"REGISTRO DESMARCADO":"HÁBITO CONCLUÍDO")}catch(e){toast.error(e instanceof Error?e.message:"ERRO AO REGISTRAR HÁBITO")}}
 return <div className="space-y-5 pb-4">
  <PageHeader title="HÁBITOS" subtitle="Acompanhe e construa hábitos melhores todos os dias." />
  <div className="flex justify-end -mt-2"><button onClick={()=>setShowForm(v=>!v)} className="gradient-primary flex items-center gap-2 rounded-xl px-5 py-3 text-[11px] font-semibold text-primary-foreground"><Plus className="h-4 w-4"/> NOVO HÁBITO</button></div>
  {showForm&&<Panel title="NOVO HÁBITO"><div className="grid gap-2 md:grid-cols-[1fr_180px_180px_auto]"><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void add()} placeholder="Nome do hábito" className="rounded-xl border border-input bg-background px-4 py-3 text-sm"/><label className="relative"><span className="pointer-events-none absolute left-4 top-2 text-[9px] text-muted-foreground">Frequência</span><select value={frequency} onChange={e=>setFrequency(e.target.value)} className="h-full w-full appearance-none rounded-xl border border-input bg-background px-4 pb-2 pt-5 text-sm"><option value="daily">DIÁRIO</option><option value="weekly">SEMANAL</option><option value="monthly">MENSAL</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4"/></label><label className="relative"><span className="pointer-events-none absolute left-4 top-2 text-[9px] text-muted-foreground">Privacidade</span><select value={privacy} onChange={e=>setPrivacy(e.target.value)} className="h-full w-full appearance-none rounded-xl border border-input bg-background px-4 pb-2 pt-5 text-sm"><option value="private">PRIVADO</option><option value="shared">COMPARTILHADO</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4"/></label><button onClick={()=>void add()} className="gradient-primary flex items-center justify-center gap-1 rounded-xl px-6 py-3 text-[10px] font-semibold text-primary-foreground"><Plus className="h-4 w-4"/> ADICIONAR</button></div></Panel>}
  {editing&&<Panel title="EDITAR HÁBITO"><div className="grid gap-2 md:grid-cols-[1fr_180px_180px_auto]"><input value={editTitle} onChange={e=>setEditTitle(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3 text-sm"/><select value={editFrequency} onChange={e=>setEditFrequency(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3 text-sm"><option value="daily">DIÁRIO</option><option value="weekly">SEMANAL</option><option value="monthly">MENSAL</option></select><select value={editPrivacy} onChange={e=>setEditPrivacy(e.target.value)} className="rounded-xl border border-input bg-background px-4 py-3 text-sm"><option value="private">PRIVADO</option><option value="shared">COMPARTILHADO</option></select><div className="flex gap-2"><button onClick={()=>void saveEdit()} className="gradient-primary rounded-xl px-5 text-[10px] font-semibold text-primary-foreground">SALVAR</button><button onClick={()=>setEditing(null)} className="rounded-xl border border-border px-4"><X className="h-4 w-4"/></button></div></div></Panel>}
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2 overflow-x-auto">{(["MEUS HÁBITOS","HÁBITOS DE PARCEIRO"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={cn("whitespace-nowrap rounded-xl border px-5 py-3 text-[10px] font-semibold",tab===t?"border-orange-500/70 bg-orange-500/10 text-orange-400":"border-border text-muted-foreground")}>{t}</button>)}</div></div>
  {list.length>0&&<Panel><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-widest text-muted-foreground">{greeting}, hoje</p><p className="mt-1 text-3xl font-semibold tracking-tight">{todayDone}/{total}</p><p className="text-xs text-muted-foreground">{total-todayDone===0?"Todos os hábitos concluídos hoje":"hábitos restantes para concluir o dia"}</p></div><div className="relative flex h-20 w-20 items-center justify-center rounded-full border-4 border-orange-500/20"><div className="absolute inset-0 rounded-full border-4 border-transparent border-t-orange-500" style={{transform:`rotate(${progress*3.6-45}deg)`}}/><span className="text-sm font-semibold text-orange-400">{progress}%</span></div></div><div className="mt-5 border-t border-border pt-4"><div className="mb-2 flex justify-between text-[9px] text-muted-foreground">{week.map((d,i)=><span key={i} className="w-7 text-center">{d}</span>)}</div><div className="flex justify-between">{week.map((_,i)=><span key={i} className={cn("flex h-7 w-7 items-center justify-center rounded-lg text-[9px]",i===currentDay?"bg-orange-500/15 text-orange-400":"bg-secondary text-muted-foreground")}>{i===currentDay?"HOJE":""}</span>)}</div></div></Panel>}
  {habits.isLoading?<p className="text-sm text-muted-foreground">Carregando hábitos...</p>:list.length===0?<Panel><div className="py-10 text-center"><div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-full border border-orange-500/40 text-2xl text-orange-400">+</div><p className="font-semibold">Nenhum hábito cadastrado</p><p className="mt-1 text-xs text-muted-foreground">Crie seu primeiro hábito acima para começar.</p></div></Panel>:<div><div className="mb-3 flex items-center justify-between"><p className="label-caps text-sm">HÁBITOS DE HOJE</p><span className="text-[10px] text-muted-foreground">{total} {total===1?"hábito":"hábitos"}</span></div><div className="grid gap-3 md:grid-cols-2">{list.map((h,i)=>{const isTodayDone=isDone(h.id);const accent=accents[i%accents.length];const currentStreak=streak(h.id);return <div key={h.id} className={cn("rounded-2xl border p-4 transition",isTodayDone?accentClasses[accent]:"border-border bg-card/70")}><div className="flex items-center gap-3"><div className={cn("flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border text-xl",accentClasses[accent])}>{iconByTitle(h.title)}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold">{h.title}</p><span className={cn("rounded-full px-2 py-1 text-[9px]",accentClasses[accent])}><Flame className="mr-1 inline h-3 w-3"/>{currentStreak} {currentStreak===1?"dia":"dias"}</span></div><p className="mt-1 text-[10px] text-muted-foreground">{labelFrequency(h.frequency)} · {h.privacy==="shared"?"Compartilhado":"Privado"}</p></div><div className="flex gap-2"><button onClick={()=>startEdit(h)} className="text-muted-foreground hover:text-primary" title="Editar"><Pencil className="h-4 w-4"/></button><button onClick={()=>void remove(h.id)} className="text-red-400/70 hover:text-red-400" title="Excluir"><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-4 flex items-center gap-2">{week.map((d,day)=><button key={day+day} onClick={()=>day===currentDay&&void toggle(h.id)} className={cn("h-8 flex-1 rounded-full border text-[8px]",day===currentDay?isTodayDone?"border-transparent bg-orange-500 text-black":"border-orange-500/50 text-orange-400":"border-border text-muted-foreground")}>{day===currentDay&&isTodayDone?<Check className="mx-auto h-3 w-3"/>:d}</button>)}</div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-secondary"><div className={cn("h-full rounded-full transition-all",isTodayDone?"w-full bg-orange-500":"w-0")} /></div></div>})}</div></div>}
  {list.length>0&&<div className="grid gap-3 sm:grid-cols-3"><Panel><p className="text-2xl font-semibold">{total}</p><p className="text-[10px] text-muted-foreground">Hábitos ativos</p></Panel><Panel><p className="text-2xl font-semibold text-orange-400">{todayDone}</p><p className="text-[10px] text-muted-foreground">Concluídos hoje</p></Panel><Panel><p className="text-2xl font-semibold">{progress}%</p><p className="text-[10px] text-muted-foreground">Progresso de hoje</p></Panel></div>}
 </div>;
}
