import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { CalendarDays, Bell, RefreshCw, CheckCircle2 } from "lucide-react";
import { PageHeader, Panel, Tag } from "@/components/ui-kit";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/integracoes")({head:()=>({meta:[{title:"INTEGRAÇÕES — MULTICAP"}]}),component:IntegracoesPage});
type Connection={id:string;google_email:string|null;calendar_id:string;sync_enabled:boolean;last_synced_at:string|null};
const fn=(name:string)=>`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/${name}`;
function IntegracoesPage(){const[connection,setConnection]=useState<Connection|null>(null);const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[push,setPush]=useState(false);const[pushBusy,setPushBusy]=useState(false);
 async function authFetch(url:string,init?:RequestInit){const{data}=await supabase.auth.getSession();if(!data.session)throw new Error("Faça login novamente.");return fetch(url,{...init,headers:{...(init?.headers||{}),Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json"}})}
 async function load(){try{const r=await authFetch(fn("google-calendar-oauth")+"?action=status");const d=await r.json();if(!r.ok)throw new Error(d.error);setConnection(d.connection??null);setPush(typeof Notification!=="undefined"&&Notification.permission==="granted")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao carregar integrações")}finally{setLoading(false)}}
 useEffect(()=>{void load();const on=(e:MessageEvent)=>{if(e.data?.type==="multicap-google-calendar-connected"){toast.success("Google Calendar conectado");void load()}};window.addEventListener("message",on);return()=>window.removeEventListener("message",on)},[]);
 async function connect(){try{const r=await authFetch(fn("google-calendar-oauth")+"?action=start");const d=await r.json();if(!r.ok)throw new Error(d.error);window.open(d.url,"google-calendar-oauth","width=520,height=700")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível conectar")}}
 async function sync(){setSyncing(true);try{const r=await authFetch(fn("google-calendar-sync"),{method:"POST",body:"{}"});const d=await r.json();if(!r.ok)throw new Error(d.error);toast.success(`Sincronizado: ${d.created} criado(s), ${d.updated} atualizado(s)`);await load()}catch(e){toast.error(e instanceof Error?e.message:"Erro na sincronização")}finally{setSyncing(false)}}
 async function disconnect(){if(!window.confirm("Desconectar o Google Calendar?"))return;try{const r=await authFetch(fn("google-calendar-oauth")+"?action=disconnect",{method:"POST",body:"{}"});if(!r.ok)throw new Error("Não foi possível desconectar");setConnection(null);toast.success("Google Calendar desconectado")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao desconectar")}}
 async function enablePush(){setPushBusy(true);try{if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw new Error("Seu navegador não suporta notificações push.");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Permissão de notificações não concedida.");const registration=await navigator.serviceWorker.register("/sw.js");const publicKey=import.meta.env.VITE_VAPID_PUBLIC_KEY;if(!publicKey)throw new Error("VITE_VAPID_PUBLIC_KEY ainda não foi configurada.");const sub=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(publicKey.replace(/-/g,"+").replace(/_/g,"/")+"=="),c=>c.charCodeAt(0))});const json=sub.toJSON();const{data:{user}}=await supabase.auth.getUser();if(!user||!json.endpoint||!json.keys?.p256dh||!json.keys.auth)throw new Error("Não foi possível registrar este dispositivo.");const{data:profile}=await supabase.from("profiles").select("household_id").eq("id",user.id).maybeSingle();const{error}=await supabase.from("push_subscriptions").upsert({user_id:user.id,household_id:profile?.household_id??null,endpoint:json.endpoint,p256dh:json.keys.p256dh,auth:json.keys.auth,user_agent:navigator.userAgent,enabled:true,updated_at:new Date().toISOString()},{onConflict:"endpoint"});if(error)throw error;setPush(true);toast.success("Notificações push ativadas")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao ativar notificações")}finally{setPushBusy(false)}}
 async function disablePush(){try{const reg=await navigator.serviceWorker.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub){await supabase.from("push_subscriptions").update({enabled:false}).eq("endpoint",sub.endpoint);await sub.unsubscribe()}setPush(false);toast.success("Notificações push desativadas")}catch(e){toast.error(e instanceof Error?e.message:"Erro ao desativar notificações")}}
 return <div className="space-y-5"><PageHeader title="INTEGRAÇÕES" subtitle="CALENDÁRIO E NOTIFICAÇÕES DO MULTICAP."/><div className="grid gap-4 lg:grid-cols-2"><Panel title="GOOGLE CALENDAR"><div className="space-y-4"><div className="flex items-start gap-3 rounded-xl border bg-secondary/30 p-4"><CalendarDays className="mt-0.5 h-5 w-5 text-primary"/><div><p className="text-sm font-semibold">SINCRONIZAÇÃO COM GOOGLE</p><p className="mt-1 text-xs text-muted-foreground">Conecte sua agenda para enviar compromissos do MULTICAP ao Google Calendar.</p></div></div>{loading?<p className="text-xs text-muted-foreground">CARREGANDO...</p>:connection?<><div className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-xs font-semibold">{connection.google_email||"CONTA GOOGLE"}</p><p className="text-[10px] text-muted-foreground">{connection.last_synced_at?`Última sincronização: ${new Date(connection.last_synced_at).toLocaleString("pt-BR")}`:"Ainda não sincronizado"}</p></div><Tag tone="success">CONECTADO</Tag></div><div className="flex gap-2"><button onClick={()=>void sync()} disabled={syncing} className="gradient-primary flex items-center gap-2 rounded-xl px-4 py-2 text-[10px] text-primary-foreground"><RefreshCw className={`h-3.5 w-3.5 ${syncing?"animate-spin":""}`}/> {syncing?"SINCRONIZANDO...":"SINCRONIZAR AGORA"}</button><button onClick={()=>void disconnect()} className="rounded-xl border px-4 py-2 text-[10px] text-danger">DESCONECTAR</button></div></>:<button onClick={()=>void connect()} className="gradient-primary w-full rounded-xl p-3 text-[10px] text-primary-foreground">CONECTAR GOOGLE CALENDAR</button>}</div></Panel><Panel title="NOTIFICAÇÕES PUSH"><div className="space-y-4"><div className="flex items-start gap-3 rounded-xl border bg-secondary/30 p-4"><Bell className="mt-0.5 h-5 w-5 text-primary"/><div><p className="text-sm font-semibold">AVISOS MESMO COM O APP FECHADO</p><p className="mt-1 text-xs text-muted-foreground">Receba alertas de tarefas vencendo no dia neste dispositivo.</p></div></div>{push?<><div className="flex items-center gap-2 rounded-xl border border-success/20 bg-success/5 p-3 text-xs"><CheckCircle2 className="h-4 w-4 text-success"/> NOTIFICAÇÕES ATIVADAS</div><button onClick={()=>void disablePush()} className="rounded-xl border px-4 py-2 text-[10px]">DESATIVAR NESTE DISPOSITIVO</button></>:<button onClick={()=>void enablePush()} disabled={pushBusy} className="gradient-primary w-full rounded-xl p-3 text-[10px] text-primary-foreground">{pushBusy?"ATIVANDO...":"ATIVAR NOTIFICAÇÕES PUSH"}</button>}</div></Panel></div></div>}
