import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { PageHeader, Panel, ProgressBar, StatCard, Tag } from "@/components/ui-kit";
import { formatCurrency } from "@/lib/finance";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { useHouseholdMembers } from "@/hooks/use-household-members";
import { useGlobalMonth, MonthSelector } from "@/hooks/use-global-month";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/investimentos")({ head: () => ({ meta: [{ title: "INVESTIMENTOS — MULTICAP" }] }), component: InvestmentsPage });
type Investment={id:string;name:string;type:string;invested:number;current_value:number;created_at:string;household_id:string};
type Transaction={id:string;date:string;description:string;category:string;pay_method:string;responsible:string;amount:number;type:string;paid:boolean;household_id:string};
const TYPES=["RENDA FIXA","TESOURO DIRETO","FII","ETF","AÇÕES","CRIPTO","OUTROS"];
function InvestmentsPage(){
 const {month,setMonth}=useGlobalMonth("investimentos");
 const inv=useHouseholdTable<Investment>("investments","id,name,type,invested,current_value,created_at,household_id");
 const tx=useHouseholdTable<Transaction>("transactions","id,date,description,category,pay_method,responsible,amount,type,paid,household_id");
 const members=useHouseholdMembers();
 const [tab,setTab]=useState<"INVESTIMENTOS"|"RESGATES">("INVESTIMENTOS");
 const [open,setOpen]=useState(false); const [selected,setSelected]=useState<Investment|null>(null); const [redemption,setRedemption]=useState(false);
 const [name,setName]=useState(""); const [type,setType]=useState("RENDA FIXA"); const [invested,setInvested]=useState(""); const [current,setCurrent]=useState("");
 const [investmentId,setInvestmentId]=useState(""); const [amount,setAmount]=useState(""); const [responsible,setResponsible]=useState("AMBAS / COMPARTILHADO"); const [description,setDescription]=useState("");
 const selectedRedemption=useMemo(()=>inv.rows.find(i=>i.id===investmentId),[inv.rows,investmentId]); const available=selectedRedemption?Number(selectedRedemption.current_value):0;
 useEffect(()=>{const handler=(event:globalThis.Event)=>{const d=(event as CustomEvent<{option?:string}>).detail;if(d?.option==="NOVO INVESTIMENTO"){setTab("INVESTIMENTOS");setName("");setType("RENDA FIXA");setInvested("");setCurrent("");setOpen(true)}if(d?.option==="NOVO RESGATE"){setTab("RESGATES");setInvestmentId("");setAmount("");setDescription("");setResponsible("AMBAS / COMPARTILHADO");setRedemption(true)}};window.addEventListener("multicap:open-create",handler);return()=>window.removeEventListener("multicap:open-create",handler)},[]);
 async function add(){const a=Number(invested.replace(",","."));const c=current===""?a:Number(current.replace(",","."));if(!name.trim()||a<=0){toast.error("PREENCHA NOME E VALOR APLICADO");return}try{await inv.insert({name:name.trim().toUpperCase(),type,invested:a,current_value:c});setOpen(false);toast.success("INVESTIMENTO SALVO")}catch(e){toast.error(e instanceof Error?e.message:"NÃO FOI POSSÍVEL SALVAR")}}
 async function redeem(){const value=Number(amount.replace(",","."));if(!selectedRedemption){toast.error("SELECIONE O INVESTIMENTO");return}if(value<=0||value>available){toast.error("INFORME UM VALOR VÁLIDO PARA O RESGATE");return}try{await inv.update(selectedRedemption.id,{current_value:available-value});await tx.insert({date:`${month}-01`,description:(description.trim()||`RESGATE — ${selectedRedemption.name}`).toUpperCase(),amount:value,type:"RECEITA",category:"RESGATE DE INVESTIMENTO",pay_method:"TRANSFERÊNCIA",responsible,paid:true});setRedemption(false);setAmount("");setDescription("");toast.success("RESGATE REALIZADO E LANÇADO COMO RECEITA")}catch(e){toast.error(e instanceof Error?e.message:"NÃO FOI POSSÍVEL REALIZAR O RESGATE")}}
 async function del(i:Investment){if(!confirm(`EXCLUIR ${i.name}?`))return;try{await inv.remove(i.id);setSelected(null);toast.success("INVESTIMENTO EXCLUÍDO")}catch(e){toast.error(e instanceof Error?e.message:"NÃO FOI POSSÍVEL EXCLUIR")}}
 const visible=inv.rows; const totalInvested=visible.reduce((s,i)=>s+Number(i.invested),0); const totalCurrent=visible.reduce((s,i)=>s+Number(i.current_value),0); const profit=totalCurrent-totalInvested;
 return <div className="space-y-5">
  <PageHeader title="INVESTIMENTOS" subtitle="APORTES, CARTEIRA, RESGATES E EVOLUÇÃO DOS SEUS INVESTIMENTOS." action={<MonthSelector month={month} setMonth={setMonth}/>}/>
  <div className="rounded-2xl border border-border bg-card p-1.5"><div className="grid grid-cols-2 gap-1"><button type="button" onClick={()=>setTab("INVESTIMENTOS")} className={`rounded-xl px-4 py-3 text-[10px] font-semibold tracking-[0.08em] transition ${tab==="INVESTIMENTOS"?"gradient-primary text-primary-foreground":"text-muted-foreground hover:bg-secondary"}`}>INVESTIMENTOS</button><button type="button" onClick={()=>setTab("RESGATES")} className={`rounded-xl px-4 py-3 text-[10px] font-semibold tracking-[0.08em] transition ${tab==="RESGATES"?"gradient-primary text-primary-foreground":"text-muted-foreground hover:bg-secondary"}`}>RESGATES</button></div></div>
  {tab==="INVESTIMENTOS"?<>
   <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="VALOR APLICADO" value={formatCurrency(totalInvested)} tone="info"/><StatCard label="VALOR ATUAL" value={formatCurrency(totalCurrent)} tone="primary"/><StatCard label="RESULTADO" value={formatCurrency(profit)} tone={profit>=0?"success":"danger"}/><StatCard label="RENTABILIDADE" value={totalInvested?`${((profit/totalInvested)*100).toFixed(1)}%`:"0,0%"} tone="success"/></div>
   <Panel title="MINHA CARTEIRA">{visible.length===0?<p className="py-8 text-center text-sm text-muted-foreground">NENHUM INVESTIMENTO CADASTRADO.</p>:<div className="grid gap-3 md:grid-cols-2">{visible.map(i=>{const p=Number(i.current_value)-Number(i.invested);const pct=Number(i.invested)?p/Number(i.invested)*100:0;return <div key={i.id} className="rounded-2xl border border-border bg-card p-4"><button type="button" onClick={()=>setSelected(i)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="label-caps text-sm">{i.name}</p><Tag>{i.type}</Tag></div><div className="text-right"><p className="font-bold">{formatCurrency(Number(i.current_value))}</p><p className={pct>=0?"text-xs text-success":"text-xs text-danger"}>{pct>=0?"+":""}{pct.toFixed(1)}%</p></div></div><div className="mt-3"><ProgressBar percent={totalCurrent?Number(i.current_value)/totalCurrent*100:0} tone="primary"/></div></button></div>})}</div>}</Panel>
  </>:<>
   <div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><StatCard label="CARTEIRA ATUAL" value={formatCurrency(totalCurrent)} tone="primary"/><StatCard label="INVESTIMENTOS" value={String(inv.rows.length)} tone="info"/><StatCard label="RESULTADO" value={formatCurrency(profit)} tone={profit>=0?"success":"danger"}/></div>
   <Panel title="RESGATES"><p className="mb-3 text-[10px] text-muted-foreground">Selecione um investimento para realizar um resgate. O formulário aparece somente após o clique.</p>{inv.rows.length===0?<p className="py-8 text-center text-sm text-muted-foreground">NENHUM INVESTIMENTO CADASTRADO.</p>:<div className="grid gap-3 md:grid-cols-2">{inv.rows.map(i=><button type="button" key={i.id} onClick={()=>{setInvestmentId(i.id);setAmount("");setDescription("");setRedemption(true)}} className="rounded-xl border border-border bg-secondary/30 p-3 text-left hover:border-primary/50"><div className="flex items-center justify-between"><div><p className="label-caps text-[12px] font-bold">{i.name}</p><p className="text-[10px] text-muted-foreground">{i.type}</p></div><p className="text-sm font-bold">{formatCurrency(Number(i.current_value))}</p></div></button>)}</div>}</Panel>
  </>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl rounded-3xl"><DialogHeader><DialogTitle className="label-caps">NOVO INVESTIMENTO</DialogTitle></DialogHeader><div className="grid gap-4 md:grid-cols-2"><label className="block md:col-span-2"><span className="label-caps mb-1 block text-[9px]">ATIVO / INVESTIMENTO</span><input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><label><span className="label-caps mb-1 block text-[9px]">TIPO</span><select value={type} onChange={e=>setType(e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm">{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label><span className="label-caps mb-1 block text-[9px]">VALOR APLICADO</span><input value={invested} onChange={e=>setInvested(e.target.value)} inputMode="decimal" className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><label className="md:col-span-2"><span className="label-caps mb-1 block text-[9px]">VALOR ATUAL</span><input value={current} onChange={e=>setCurrent(e.target.value)} inputMode="decimal" placeholder="Igual ao aplicado" className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><button type="button" onClick={()=>void add()} className="gradient-primary rounded-xl px-4 py-2.5 text-[10px] font-semibold text-primary-foreground md:col-span-2">SALVAR INVESTIMENTO</button></div></DialogContent></Dialog>
  <Dialog open={redemption} onOpenChange={setRedemption}><DialogContent className="max-w-lg rounded-3xl"><DialogHeader><DialogTitle className="label-caps">NOVO RESGATE</DialogTitle></DialogHeader><div className="space-y-4"><label><span className="label-caps mb-1 block text-[9px]">INVESTIMENTO</span><select value={investmentId} onChange={e=>setInvestmentId(e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"><option value="">SELECIONE</option>{inv.rows.map(i=><option key={i.id} value={i.id}>{i.name} — {formatCurrency(Number(i.current_value))}</option>)}</select></label>{selectedRedemption&&<div className="rounded-xl border bg-secondary/30 p-3 text-xs">DISPONÍVEL: <strong>{formatCurrency(available)}</strong></div>}<label><span className="label-caps mb-1 block text-[9px]">VALOR DO RESGATE</span><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0,00" className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><label><span className="label-caps mb-1 block text-[9px]">RESPONSÁVEL</span><select value={responsible} onChange={e=>setResponsible(e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"><option>AMBAS / COMPARTILHADO</option>{(members.data??[]).map(m=><option key={m.id} value={m.name}>{m.name}</option>)}</select></label><label><span className="label-caps mb-1 block text-[9px]">DESCRIÇÃO</span><input value={description} onChange={e=>setDescription(e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><button type="button" onClick={()=>void redeem()} className="gradient-primary w-full rounded-xl px-5 py-2.5 text-[10px] font-semibold text-primary-foreground">REALIZAR RESGATE</button></div></DialogContent></Dialog>
  <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-w-md rounded-3xl"><DialogHeader><DialogTitle className="label-caps">DETALHES DO INVESTIMENTO</DialogTitle></DialogHeader>{selected&&<div className="space-y-3"><div className="rounded-2xl border bg-secondary/30 p-4"><p className="label-caps text-sm font-bold">{selected.name}</p><p className="mt-2 text-2xl font-bold">{formatCurrency(Number(selected.current_value))}</p><p className="mt-1 text-xs text-muted-foreground">{selected.type}</p></div><div className="flex gap-2"><button type="button" onClick={()=>void del(selected)} className="w-full rounded-xl border border-danger/50 px-3 py-2.5 text-[10px] font-semibold text-danger">EXCLUIR INVESTIMENTO</button></div></div>}</DialogContent></Dialog>
 </div>
}
