import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { PageHeader, Panel, ProgressBar, StatCard, Tag } from "@/components/ui-kit";
import { formatCurrency, requiredMonthlyContribution, futureValue, monthsToTarget } from "@/lib/finance";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { MonthSelector, useGlobalMonth } from "@/hooks/use-global-month";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/investimentos")({ head: () => ({ meta: [{ title: "INVESTIMENTOS — MULTICAP" }] }), component: InvestmentsPage });
type Row = { id:string; name:string; type:string; invested:number; current_value:number; created_at:string; household_id:string };
const TYPES=["RENDA FIXA","TESOURO DIRETO","FII","ETF","AÇÕES","CRIPTO","OUTROS"];

function InvestmentsPage(){
  const {month,setMonth}=useGlobalMonth("investimentos");
  const {rows,insert,update,remove,isLoading}=useHouseholdTable<Row>("investments","id,name,type,invested,current_value,created_at,household_id");
  const [open,setOpen]=useState(false);
  const [selected,setSelected]=useState<Row|null>(null);
  const [name,setName]=useState(""); const [type,setType]=useState("RENDA FIXA"); const [invested,setInvested]=useState(""); const [current,setCurrent]=useState("");
  const [target,setTarget]=useState(100000); const [initial,setInitial]=useState(0); const [months,setMonths]=useState(60); const [rate,setRate]=useState(10); const [monthly,setMonthly]=useState(1000);
  const visible=rows.filter(i=>String(i.created_at||"").startsWith(month));
  const totalInvested=visible.reduce((s,i)=>s+Number(i.invested),0); const totalCurrent=visible.reduce((s,i)=>s+Number(i.current_value),0); const profit=totalCurrent-totalInvested;
  function reset(){setName("");setType("RENDA FIXA");setInvested("");setCurrent("");setOpen(false)}
  function openNew(){setName("");setType("RENDA FIXA");setInvested("");setCurrent("");setOpen(true)}
  useEffect(()=>{const openHandler=()=>openNew();const handler=(event:globalThis.Event)=>{const detail=(event as CustomEvent<{option?:string}>).detail;if(detail?.option==="NOVO INVESTIMENTO")openHandler()};window.addEventListener("multicap:open-create",handler);if(sessionStorage.getItem("multicap:pending-create")==="NOVO INVESTIMENTO"){sessionStorage.removeItem("multicap:pending-create");openHandler()}return()=>window.removeEventListener("multicap:open-create",handler)},[]);
  async function add(){const a=Number(invested.replace(",","."));const c=current===""?a:Number(current.replace(",","."));if(!name.trim()||a<=0){toast.error("PREENCHA NOME E VALOR APLICADO");return}try{await insert({name:name.trim().toUpperCase(),type,invested:a,current_value:c});reset();toast.success("INVESTIMENTO SALVO")}catch(e){toast.error(e instanceof Error?e.message:"NÃO FOI POSSÍVEL SALVAR")}}
  async function edit(i:Row){const value=prompt("VALOR ATUAL DO INVESTIMENTO",String(i.current_value));if(value===null)return;const n=Number(value.replace(",","."));if(!Number.isFinite(n)||n<0){toast.error("INFORME UM VALOR VÁLIDO");return}try{await update(i.id,{current_value:n});setSelected({...i,current_value:n});toast.success("VALOR ATUALIZADO")}catch(e){toast.error(e instanceof Error?e.message:"NÃO FOI POSSÍVEL ATUALIZAR")}}
  async function del(i:Row){if(!confirm(`EXCLUIR ${i.name}?`))return;try{await remove(i.id);setSelected(null);toast.success("INVESTIMENTO EXCLUÍDO")}catch(e){toast.error(e instanceof Error?e.message:"NÃO FOI POSSÍVEL EXCLUIR")}}
  const annual=rate/100;
  return <div className="space-y-5">
    <PageHeader title="INVESTIMENTOS" subtitle="APORTES, CARTEIRA E EVOLUÇÃO DOS SEUS INVESTIMENTOS." action={<MonthSelector month={month} setMonth={setMonth}/>}/>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="VALOR APLICADO" value={formatCurrency(totalInvested)} tone="info"/><StatCard label="VALOR ATUAL" value={formatCurrency(totalCurrent)} tone="primary"/><StatCard label="RESULTADO" value={formatCurrency(profit)} tone={profit>=0?"success":"danger"}/><StatCard label="RENTABILIDADE" value={totalInvested?`${((profit/totalInvested)*100).toFixed(1)}%`:"0,0%"} tone="success"/></div>
    <Panel title={`MINHA CARTEIRA — ${month}`}>
      {isLoading?<p className="py-8 text-center text-sm text-muted-foreground">Carregando...</p>:visible.length===0?<div className="py-8 text-center"><p className="text-sm text-muted-foreground">NENHUM INVESTIMENTO CADASTRADO NESTE MÊS.</p></div>:<div className="grid gap-3 md:grid-cols-2">{visible.map(i=>{const p=Number(i.current_value)-Number(i.invested);const pct=Number(i.invested)?p/Number(i.invested)*100:0;return <div key={i.id} className="rounded-2xl border border-border bg-card p-4"><button type="button" onClick={()=>setSelected(i)} className="w-full text-left"><div className="flex items-start justify-between gap-3"><div><p className="label-caps text-sm">{i.name}</p><Tag>{i.type}</Tag></div><div className="text-right"><p className="font-bold">{formatCurrency(Number(i.current_value))}</p><p className={pct>=0?"text-xs text-success":"text-xs text-danger"}>{pct>=0?"+":""}{pct.toFixed(1)}%</p></div></div><div className="mt-3"><ProgressBar percent={totalCurrent?Number(i.current_value)/totalCurrent*100:0} tone="primary"/></div></button></div>})}</div>}
    </Panel>
    <Panel title="CALCULADORA DE APORTES"><div className="grid gap-3 md:grid-cols-5">{[["OBJETIVO",target,setTarget],["VALOR INICIAL",initial,setInitial],["PRAZO (MESES)",months,setMonths],["TAXA A.A. (%)",rate,setRate],["APORTE MENSAL",monthly,setMonthly]].map(([label,value,setter])=><label key={String(label)}><span className="label-caps text-[10px] text-muted-foreground">{String(label)}</span><input type="number" value={value as number} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label>)}</div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="gradient-soft rounded-xl border border-primary/40 p-4"><p className="label-caps text-[10px] text-muted-foreground">APORTE NECESSÁRIO</p><p className="mt-1 text-lg font-bold text-primary">{formatCurrency(requiredMonthlyContribution(target,initial,months,annual))}</p></div><div className="rounded-xl border border-border bg-secondary/40 p-4"><p className="label-caps text-[10px] text-muted-foreground">MONTANTE FINAL</p><p className="mt-1 text-lg font-bold">{formatCurrency(futureValue(monthly,initial,months,annual))}</p></div><div className="rounded-xl border border-border bg-secondary/40 p-4"><p className="label-caps text-[10px] text-muted-foreground">TEMPO NECESSÁRIO</p><p className="mt-1 text-lg font-bold">{monthsToTarget(target,monthly,initial,annual)} meses</p></div></div></Panel>
    <Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)reset()}}><DialogContent className="max-w-2xl rounded-3xl"><DialogHeader><DialogTitle className="label-caps">NOVO INVESTIMENTO</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><label className="block md:col-span-2"><span className="label-caps mb-1.5 block text-[9px] font-semibold text-muted-foreground">ATIVO / INVESTIMENTO</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="CDB, Tesouro, ETF..." className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><label className="block"><span className="label-caps mb-1.5 block text-[9px] font-semibold text-muted-foreground">TIPO</span><select value={type} onChange={e=>setType(e.target.value)} className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm">{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label className="block"><span className="label-caps mb-1.5 block text-[9px] font-semibold text-muted-foreground">VALOR APLICADO</span><input value={invested} onChange={e=>setInvested(e.target.value)} inputMode="decimal" placeholder="0,00" className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label><label className="block md:col-span-2"><span className="label-caps mb-1.5 block text-[9px] font-semibold text-muted-foreground">VALOR ATUAL</span><input value={current} onChange={e=>setCurrent(e.target.value)} inputMode="decimal" placeholder="Igual ao aplicado" className="w-full rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/></label></div><button type="button" onClick={()=>void add()} className="gradient-primary w-full rounded-xl px-4 py-2.5 text-[10px] font-semibold text-primary-foreground">SALVAR INVESTIMENTO</button></div></DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-w-md rounded-3xl"><DialogHeader><DialogTitle className="label-caps">DETALHES DO INVESTIMENTO</DialogTitle></DialogHeader>{selected&&<div className="space-y-3"><div className="rounded-2xl border bg-secondary/30 p-4"><div className="flex items-center justify-between gap-3"><div><p className="label-caps text-sm font-bold">{selected.name}</p><p className="mt-1 text-xs text-muted-foreground">{selected.type}</p></div><p className="text-2xl font-bold">{formatCurrency(Number(selected.current_value))}</p></div></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border p-3"><p className="label-caps text-[9px] text-muted-foreground">VALOR APLICADO</p><p className="mt-1 font-bold">{formatCurrency(Number(selected.invested))}</p></div><div className="rounded-xl border p-3"><p className="label-caps text-[9px] text-muted-foreground">RESULTADO</p><p className="mt-1 font-bold">{formatCurrency(Number(selected.current_value)-Number(selected.invested))}</p></div></div><div className="flex gap-2"><button type="button" onClick={()=>void edit(selected)} className="flex-1 rounded-xl border border-primary/60 px-3 py-2.5 text-[10px] font-semibold text-primary">ATUALIZAR VALOR</button><button type="button" onClick={()=>void del(selected)} className="rounded-xl border border-danger/50 px-3 py-2.5 text-[10px] font-semibold text-danger">EXCLUIR</button></div></div>}</DialogContent></Dialog>
  </div>
}
