import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Check } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Panel, StatCard, Tag } from "@/components/ui-kit";
import { formatCurrency } from "@/lib/finance";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { cn } from "@/lib/utils";
export const Route=createFileRoute("/lista")({head:()=>({meta:[{title:"LISTA DE COMPRAS — MULTICAP"}]}),component:ShoppingPage});
type List={id:string;name:string;archived:boolean;household_id:string};type Item={id:string;list_id:string;name:string;category:string;qty:number;unit:string;price:number;priority:string;done:boolean;household_id:string};
function ShoppingPage(){const lists=useHouseholdTable<List>("shopping_lists","id,name,archived,household_id");const items=useHouseholdTable<Item>("shopping_items","id,list_id,name,category,qty,unit,price,priority,done,household_id");const [active,setActive]=useState("");const [listName,setListName]=useState("");const [name,setName]=useState("");const [price,setPrice]=useState("");const [qty,setQty]=useState("1");
 const current=active?lists.rows.find(x=>x.id===active):lists.rows[0]; const currentItems=current?items.rows.filter(i=>i.list_id===current.id):[];const total=currentItems.reduce((s,i)=>s+Number(i.qty)*Number(i.price),0);
 async function addList(){if(!listName.trim())return;try{const x=await lists.insert({name:listName.trim().toUpperCase(),archived:false});setListName("");setActive(x.id);toast.success("LISTA CRIADA")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível criar")}}
 async function addItem(){if(!current||!name.trim())return toast.error("CRIE/SELECIONE UMA LISTA");try{await items.insert({list_id:current.id,name:name.trim().toUpperCase(),price:Number(price.replace(',','.'))||0,qty:Number(qty)||1,unit:"UN",category:"OUTROS",priority:"MÉDIA",done:false});setName("");setPrice("")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar")}}
 async function toggle(i:Item){try{await items.update(i.id,{done:!i.done})}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível atualizar")}}
 return <div className="space-y-5"><PageHeader title="LISTA DE COMPRAS" subtitle="Cadastre listas e itens reais do seu grupo."/><Panel title="NOVA LISTA"><div className="flex gap-2"><input value={listName} onChange={e=>setListName(e.target.value)} placeholder="Ex.: Mercado" className="flex-1 rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><button onClick={addList} className="gradient-primary label-caps rounded-xl px-4 text-[10px] text-primary-foreground">CRIAR LISTA</button></div></Panel><div className="flex flex-wrap gap-2">{lists.rows.map(l=><button key={l.id} onClick={()=>setActive(l.id)} className={cn("label-caps rounded-xl border px-4 py-2 text-[11px]",(current?.id===l.id)?"border-primary bg-primary/15 text-primary":"border-border text-muted-foreground")}>{l.name}</button>)}</div>{current?<><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><StatCard label="ITENS" value={String(currentItems.length)} tone="info"/><StatCard label="CONCLUÍDOS" value={String(currentItems.filter(i=>i.done).length)} tone="success"/><StatCard label="TOTAL ESTIMADO" value={formatCurrency(total)} tone="primary"/></div><Panel title={`NOVO ITEM — ${current.name}`}><div className="grid gap-3 md:grid-cols-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Produto" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm md:col-span-2"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="1" placeholder="Qtd" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Preço" inputMode="decimal" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><button onClick={addItem} className="gradient-primary label-caps rounded-xl px-4 py-2.5 text-[10px] text-primary-foreground md:col-span-2">ADICIONAR ITEM</button></div></Panel><Panel title="ITENS"><ul className="divide-y divide-border">{currentItems.map(i=><li key={i.id} className="flex items-center gap-3 py-3"><button onClick={()=>toggle(i)} className={cn("flex h-8 w-8 items-center justify-center rounded-lg border",i.done?"gradient-primary border-transparent text-primary-foreground":"border-border text-transparent")}><Check className="h-4 w-4"/></button><div className="flex-1"><p className={cn("label-caps text-[11px]",i.done&&"line-through opacity-60")}>{i.name}</p><div className="mt-1 flex gap-2"><Tag>{i.qty} {i.unit}</Tag><Tag>{i.priority}</Tag></div></div><span className="text-sm font-semibold">{formatCurrency(Number(i.qty)*Number(i.price))}</span></li>)}{currentItems.length===0&&<li className="py-8 text-center text-sm text-muted-foreground">Nenhum item cadastrado.</li>}</ul></Panel></>:<p className="py-8 text-center text-sm text-muted-foreground">Crie sua primeira lista.</p>}</div>}
