import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/use-auth";

export const Route = createFileRoute("/login")({ component: LoginPage });

function GoogleIcon() {
  return <svg viewBox="0 0 48 48" className="h-5 w-5"><path fill="#FFC107" d="M43.6 20.5H42V20H24v8h11.3c-1.6 4.6-6 8-11.3 8-6.6 0-12-5.4-12-12s5.4-12 12-12c3.1 0 5.9 1.2 8 3.1l5.7-5.7C34.6 6 29.6 4 24 4 12.9 4 4 12.9 4 24s8.9 20 20 20 20-8.9 20-20c0-1.3-.1-2.7-.4-3.5z"/><path fill="#FF3D00" d="M6.3 14.7l6.6 4.8C14.6 15.9 18.9 13 24 13c3.1 0 5.9 1.2 8 3.1l5.7-5.7C34.6 6 29.6 4 24 4c-7.5 0-14 4.2-17.7 10.7z"/><path fill="#4CAF50" d="M24 44c5.5 0 10.4-1.9 14.3-5.1l-6.6-5.6c-2 1.5-4.6 2.4-7.7 2.4-5.3 0-9.7-3.4-11.3-8.1l-6.6 5.1C9.9 39.8 16.4 44 24 44z"/><path fill="#1976D2" d="M43.6 20.5H42V20H24v8h11.3c-.8 2.3-2.3 4.2-11.3 5.6l6.6 5.6C41.4 35.9 44 30.4 44 24c0-1.3-.1-2.7-.4-3.5z"/></svg>;
}

function LoginPage() {
  const { signInWithGoogle, signInWithEmail, signUpWithEmail, session } = useAuth();
  const navigate = useNavigate();
  const [mode, setMode] = useState<"login" | "signup">("signup");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (session) void navigate({ to: "/" }); }, [session, navigate]);
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); setError(null); setMessage(null); setLoading(true); try { if (mode === "signup") { if (password !== confirmPassword) throw new Error("AS SENHAS NÃO COINCIDEM"); const result = await signUpWithEmail(email, password, name); if (result.needsConfirmation) setMessage("Cadastro criado. Verifique seu e-mail para confirmar a conta e entrar no Harmony Hub."); } else { await signInWithEmail(email, password); } } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível concluir a operação. Tente novamente."); } finally { setLoading(false); } }
  async function handleGoogle() { setError(null); setLoading(true); try { await signInWithGoogle(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível iniciar o login com o Google. Tente novamente."); setLoading(false); } }
  return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="w-full max-w-sm space-y-6"><div className="flex flex-col items-center gap-3 text-center"><span className="gradient-primary flex h-14 w-14 items-center justify-center rounded-2xl text-xl font-black text-primary-foreground">H</span><div><h1 className="label-caps text-2xl tracking-[0.2em]">HARMONY HUB</h1><p className="mt-1 text-sm text-muted-foreground">Gestão financeira e de rotina para casais e famílias.</p></div></div>
    <div className="flex rounded-xl border border-border p-1"><button type="button" onClick={()=>{setMode("signup");setError(null);setMessage(null)}} className={`label-caps flex-1 rounded-lg py-2 text-[11px] ${mode==="signup"?"bg-primary text-primary-foreground":"text-muted-foreground"}`}>CRIAR CONTA</button><button type="button" onClick={()=>{setMode("login");setError(null);setMessage(null)}} className={`label-caps flex-1 rounded-lg py-2 text-[11px] ${mode==="login"?"bg-primary text-primary-foreground":"text-muted-foreground"}`}>ENTRAR</button></div>
    <form onSubmit={handleSubmit} className="space-y-3">{mode==="signup"&&<div><label className="label-caps text-[11px] text-muted-foreground">Seu nome</label><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex: Maria" className="mt-1 w-full rounded-xl border border-border bg-secondary/60 px-3 py-3 text-sm text-foreground outline-none focus:border-primary"/></div>}<div><label className="label-caps text-[11px] text-muted-foreground">E-mail</label><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com" className="mt-1 w-full rounded-xl border border-border bg-secondary/60 px-3 py-3 text-sm text-foreground outline-none focus:border-primary"/></div><div><label className="label-caps text-[11px] text-muted-foreground">Senha</label><input required type="password" minLength={6} autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo de 6 caracteres" className="mt-1 w-full rounded-xl border border-border bg-secondary/60 px-3 py-3 text-sm text-foreground outline-none focus:border-primary"/></div>{mode==="signup"&&<div><label className="label-caps text-[11px] text-muted-foreground">Confirmar senha</label><input required type="password" minLength={6} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Repita sua senha" className="mt-1 w-full rounded-xl border border-border bg-secondary/60 px-3 py-3 text-sm text-foreground outline-none focus:border-primary"/></div>}{error&&<p className="text-sm text-destructive">{error}</p>}{message&&<p className="text-sm text-primary">{message}</p>}<button type="submit" disabled={loading} className="gradient-primary w-full rounded-xl px-4 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-60">{loading?(mode==="signup"?"CRIANDO CONTA...":"ENTRANDO..."):(mode==="signup"?"CRIAR CONTA":"ENTRAR")}</button></form>
    <div className="flex items-center gap-3"><div className="h-px flex-1 bg-border"/><span className="text-[10px] text-muted-foreground">OU</span><div className="h-px flex-1 bg-border"/></div><button onClick={handleGoogle} disabled={loading} className="flex w-full items-center justify-center gap-3 rounded-xl border border-border bg-secondary/60 px-4 py-3 text-sm font-medium text-foreground transition-colors hover:border-primary disabled:opacity-60"><GoogleIcon/>Continuar com Google</button><p className="text-center text-xs text-muted-foreground">Ao criar sua conta, você poderá criar sua casa/família no próximo passo.</p>
  </div></div>;
}
