import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { PageHeader, Panel, ProgressBar, StatCard, Tag, PersonDot } from "@/components/ui-kit";
import { formatCurrency, calculateGoalProgress } from "@/lib/finance";
import { useHouseholdTable } from "@/hooks/use-household-data";

export const Route = createFileRoute("/metas")({ head: () => ({ meta: [{ title: "METAS E CAIXINHAS — MULTICAP" }] }), component: GoalsPage });
type Row={id:string;name:string;current_amount:number;target_amount:number;deadline:string|null;monthly:number;responsible:string;shared:boolean;household_id:string};
function GoalsPage(){const {rows,insert,update,remove,isLoading}=useHouseholdTable<Row>("goals","id,name,current_amount,target_amount,deadline,monthly,responsible,shared,household_id");const [name,setName]=useState("");const [target,setTarget]=useState("");const [monthly,setMonthly]=useState("");
 const saved=rows.reduce((s,g)=>s+Number(g.current_amount),0), total=rows.reduce((s,g)=>s+Number(g.target_amount),0), aporte=rows.reduce((s,g)=>s+Number(g.monthly),0);
 async function add(){const t=Number(target.replace(",","."));if(!name.trim()||!t){toast.error("PREENCHA NOME E OBJETIVO");return};try{await insert({name:name.trim().toUpperCase(),target_amount:t,current_amount:0,monthly:Number(monthly.replace(",","."))||0,responsible:"AMBAS",shared:true,deadline:null});setName("");setTarget("");setMonthly("");toast.success("META CRIADA")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar")}}
 async function contribute(g:Row){const value=window.prompt("Valor da contribuição:",String(g.monthly||0));if(!value)return;const n=Number(value.replace(",","."));if(!n||n<=0)return;try{await update(g.id,{current_amount:Math.min(Number(g.target_amount),Number(g.current_amount)+n) });toast.success("CONTRIBUIÇÃO REGISTRADA")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível atualizar")}}
 async function del(g:Row){if(!window.confirm(`Excluir ${g.name}?`))return;try{await remove(g.id);toast.success("META EXCLUÍDA")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível excluir")}}
 return <div className="space-y-5"><PageHeader title="METAS E CAIXINHAS" subtitle="Objetivos do casal e reservas individuais."/><div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><StatCard label="GUARDADO" value={formatCurrency(saved)} tone="success"/><StatCard label="OBJETIVO TOTAL" value={formatCurrency(total)} tone="primary"/><StatCard label="APORTE MENSAL" value={formatCurrency(aporte)} tone="info"/></div><Panel title="NOVA META"><div className="grid gap-3 md:grid-cols-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da meta" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm md:col-span-2"/><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="Objetivo" inputMode="decimal" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><input value={monthly} onChange={e=>setMonthly(e.target.value)} placeholder="Aporte mensal" inputMode="decimal" className="rounded-xl border border-input bg-background px-3 py-2.5 text-sm"/><button onClick={add} className="gradient-primary rounded-xl px-4 py-2.5 text-[11px] text-primary-foreground md:col-span-4">CRIAR META</button></div></Panel><div className="grid gap-3 md:grid-cols-2">{isLoading?<p className="py-8 text-center text-sm text-muted-foreground md:col-span-2">Carregando...</p>:rows.length===0?<p className="py-8 text-center text-sm text-muted-foreground md:col-span-2">Nenhuma meta cadastrada.</p>:rows.map(g=>{const percent=calculateGoalProgress(Number(g.current_amount),Number(g.target_amount));return <Panel key={g.id}><div className="flex items-start justify-between gap-2"><div><p className="label-caps text-sm">{g.name}</p><div className="mt-1 flex items-center gap-2"><Tag tone={g.shared?"primary":"neutral"}>{g.shared?"COMPARTILHADA":"PRIVADA"}</Tag><PersonDot name={g.responsible}/></div></div><span className="label-caps text-xs text-primary">{Math.round(percent)}%</span></div><p className="mt-3 text-sm">{formatCurrency(Number(g.current_amount))} <span className="text-muted-foreground">/ {formatCurrency(Number(g.target_amount))}</span></p><div className="mt-2"><ProgressBar percent={percent} tone="primary"/></div><div className="mt-2 text-[11px] text-muted-foreground">Aporte {formatCurrency(Number(g.monthly))}/mês</div><div className="mt-3 flex gap-2"><button onClick={()=>contribute(g)} className="gradient-primary rounded-lg px-3 py-1.5 text-[10px] text-primary-foreground">ADICIONAR</button><button onClick={()=>del(g)} className="rounded-lg border border-border px-3 py-1.5 text-[10px] text-danger">EXCLUIR</button></div></Panel>})}</div></div>}
