import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Plus, LayoutDashboard, ArrowLeftRight, Wallet, Settings, RefreshCw, LogOut, Bell, AlertCircle, MoreHorizontal } from "lucide-react";
import { navGroups, quickAddOptions } from "./nav";
import { cn } from "@/lib/utils";
import { useAuth } from "@/hooks/use-auth";
import { useHouseholdTable } from "@/hooks/use-household-data";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

const bottomItems = [
  { label: "INÍCIO", to: "/", icon: LayoutDashboard },
  { label: "FLUXO", to: "/fluxo", icon: ArrowLeftRight },
  { label: "AJUSTES", to: "/configuracoes", icon: Settings },
  { label: "MAIS", to: "/mais", icon: MoreHorizontal },
];
const quickRoutes: Record<string,string> = { "NOVA DESPESA":"/fluxo?tipo=DESPESA", "NOVA RECEITA":"/fluxo?tipo=RECEITA", "NOVA PARCELA":"/parcelados", "NOVA ASSINATURA":"/assinatura", "NOVO INVESTIMENTO":"/investimentos", "NOVO RESGATE":"/resgate", "NOVA META":"/metas", "NOVO CUSTO FIXO":"/custos-fixos" };
function QuickAdd({className}:{className?:string}){const[open,setOpen]=useState(false);const navigate=useNavigate();async function openRegistration(option:string){const destination=quickRoutes[option]??"/";setOpen(false);sessionStorage.setItem("multicap:pending-create",option);await navigate({to:destination as never});const fire=()=>window.dispatchEvent(new CustomEvent("multicap:open-create",{detail:{source:"quick-add",option,title:option}}));window.setTimeout(fire,50);window.setTimeout(fire,250);window.setTimeout(fire,600)}return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button type="button" aria-label="CADASTRO RÁPIDO" className={cn("gradient-primary shadow-elegant flex h-14 w-14 items-center justify-center rounded-2xl text-primary-foreground transition-all hover:-translate-y-1 hover:shadow-xl active:scale-95",className)}><Plus className="h-7 w-7" strokeWidth={2.5}/></button></DialogTrigger><DialogContent className="max-w-md rounded-3xl"><DialogHeader><DialogTitle className="label-caps text-base">CADASTRO RÁPIDO</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-2">{quickAddOptions.map(option=><button key={option.label} type="button" onClick={()=>void openRegistration(option.label)} className="label-caps rounded-xl border border-border/70 bg-secondary/60 px-3 py-3 text-center text-[11px] text-foreground transition-all hover:border-primary hover:bg-primary/5 hover:text-primary">{option.label}</button>)}</div></DialogContent></Dialog>}
type TaskNotice={id:string;title:string;due_date:string|null;completed:boolean;household_id:string};
function Notifications(){const tasks=useHouseholdTable<TaskNotice>("tasks","id,title,due_date,completed,household_id","due_date");const[open,setOpen]=useState(false);const[todayKey,setTodayKey]=useState("");useEffect(()=>setTodayKey(new Date().toISOString().slice(0,10)),[]);const pending=useMemo(()=>tasks.rows.filter(t=>!t.completed&&t.due_date&&t.due_date<=todayKey),[tasks.rows,todayKey]);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button type="button" aria-label="NOTIFICAÇÕES" className="relative rounded-xl border border-border/70 bg-card p-2.5 text-muted-foreground transition-all hover:border-primary/40 hover:text-primary"><Bell className="h-4 w-4"/>{pending.length>0&&<span className="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-primary px-1 text-[9px] font-bold text-primary-foreground">{pending.length>9?"9+":pending.length}</span>}</button></DialogTrigger><DialogContent className="max-w-md rounded-3xl"><DialogHeader><DialogTitle className="label-caps">NOTIFICAÇÕES</DialogTitle></DialogHeader><div className="space-y-2">{pending.length===0?<div className="rounded-2xl border border-dashed p-6 text-center"><Bell className="mx-auto mb-2 h-7 w-7 text-muted-foreground"/><p className="text-sm font-semibold">NENHUMA PENDÊNCIA</p></div>:pending.map(task=><div key={task.id} className="flex items-start gap-3 rounded-xl border p-3"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-primary"/><div><p className="text-sm font-semibold">{task.title}</p><p className="text-[10px] text-muted-foreground">{task.due_date===todayKey?"VENCE HOJE":"ATRASADA"}</p></div></div>)}</div></DialogContent></Dialog>}
function SyncIndicator(){return <div className="hidden items-center gap-2 rounded-full border border-success/20 bg-success/5 px-3 py-1.5 text-[10px] text-success lg:flex"><RefreshCw className="h-3.5 w-3.5"/><span className="label-caps">SINCRONIZADO</span></div>}
function UserMenu(){const{profile,user,signOut}=useAuth();const displayName=profile?.name??user?.email??"USUÁRIO";const initials=profile?.initials??displayName.slice(0,2).toUpperCase();return <DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="flex items-center gap-2 rounded-xl border border-transparent p-1.5"><span className="flex h-9 w-9 items-center justify-center rounded-full text-[11px] font-bold text-primary-foreground shadow-sm" style={{backgroundColor:profile?.color??"#FF6B00"}}>{initials}</span><div className="hidden leading-tight sm:block"><p className="label-caps text-[11px] font-semibold">{displayName}</p><p className="text-[10px] text-muted-foreground">{user?.email}</p></div></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="rounded-xl"><DropdownMenuItem onClick={()=>void signOut()}><LogOut className="mr-2 h-4 w-4"/>SAIR</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
export function AppShell({children}:{children:ReactNode}){const pathname=useRouterState({select:s=>s.location.pathname});return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r border-sidebar-border bg-sidebar/95 backdrop-blur-xl lg:flex"><div className="flex items-center gap-3 border-b border-sidebar-border/70 px-5 py-6"><span className="gradient-primary flex h-10 w-10 items-center justify-center rounded-xl text-sm font-black text-primary-foreground shadow-lg">M</span><div><span className="label-caps block text-lg font-bold tracking-[0.2em]">MULTICAP</span><span className="text-[9px] text-muted-foreground">GESTÃO FINANCEIRA</span></div></div><nav className="flex-1 space-y-6 overflow-y-auto px-3 py-5 pb-8">{navGroups.map(group=><div key={group.group}><p className="label-caps px-3 pb-2 text-[9px] font-semibold tracking-[0.16em] text-muted-foreground/80">{group.group}</p><div className="space-y-1">{group.items.map(item=><Link key={item.to} to={item.to as never} className={cn("label-caps flex items-center gap-3 rounded-xl border border-transparent px-3 py-2.5 text-[11px]",pathname===item.to?"gradient-soft border-primary/30 font-semibold text-primary":"text-muted-foreground hover:bg-sidebar-accent hover:text-foreground")}><item.icon className="h-4 w-4"/>{item.label}</Link>)}</div></div>)}</nav></aside><div className="lg:pl-64"><div className="sticky top-0 z-20 flex min-h-16 items-center justify-between gap-3 border-b border-border/60 bg-background/85 px-4 py-3 backdrop-blur-xl lg:px-8"><SyncIndicator/><div className="flex items-center gap-2"><Notifications/><UserMenu/></div></div><main className="mx-auto w-full max-w-7xl space-y-6 px-4 pb-32 pt-6 lg:px-8 lg:pb-12">{children}</main></div><div className="fixed bottom-6 right-6 z-50 hidden lg:block"><QuickAdd/></div><nav className="fixed inset-x-0 bottom-0 z-40 flex h-[calc(68px+env(safe-area-inset-bottom))] items-end justify-around border-t border-border/70 bg-background/95 px-1 pb-[calc(8px+env(safe-area-inset-bottom))] pt-2 shadow-[0_-12px_35px_-25px_rgba(0,0,0,0.9)] backdrop-blur-xl lg:hidden">{bottomItems.slice(0,2).map(item=><BottomLink key={item.to} item={item} active={pathname===item.to}/>)}<div className="relative -mt-8 flex w-16 justify-center"><QuickAdd className="h-14 w-14 rounded-full shadow-xl ring-4 ring-background"/></div>{bottomItems.slice(2).map(item=><BottomLink key={item.to} item={item} active={pathname===item.to}/>)}</nav></div>}
function BottomLink({item,active}:{item:(typeof bottomItems)[number];active:boolean}){return <Link to={item.to as never} className={cn("label-caps flex min-h-12 w-16 flex-col items-center justify-center gap-1 rounded-xl py-1 text-[9px]",active?"bg-primary/10 font-semibold text-primary":"text-muted-foreground")}><item.icon className="h-5 w-5"/>{item.label}</Link>}
