/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CustosFixosRouteImport } from './routes/custos-fixos'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as ParceladosRouteImport } from './routes/parcelados'
import { Route as ResgateRouteImport } from './routes/resgate'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as TarefasDomesticasRouteImport } from './routes/tarefas-domesticas'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosFixosRoute = CustosFixosRouteImport.update({
  id: '/custos-fixos',
  path: '/custos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceladosRoute = ParceladosRouteImport.update({
  id: '/parcelados',
  path: '/parcelados',
  getParentRoute: () => rootRouteImport,
} as any)
const ResgateRoute = ResgateRouteImport.update({
  id: '/resgate',
  path: '/resgate',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasDomesticasRoute = TarefasDomesticasRouteImport.update({
  id: '/tarefas-domesticas',
  path: '/tarefas-domesticas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anotacoes': typeof AnotacoesRoute
  '/assinatura': typeof AssinaturaRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/faturas': typeof FaturasRoute
  '/fluxo': typeof FluxoRoute
  '/habitos': typeof HabitosRoute
  '/integracoes': typeof IntegracoesRoute
  '/investimentos': typeof InvestimentosRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/mercado': typeof MercadoRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/parcelados': typeof ParceladosRoute
  '/resgate': typeof ResgateRoute
  '/tarefas': typeof TarefasRoute
  '/tarefas-domesticas': typeof TarefasDomesticasRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anotacoes': typeof AnotacoesRoute
  '/assinatura': typeof AssinaturaRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/faturas': typeof FaturasRoute
  '/fluxo': typeof FluxoRoute
  '/habitos': typeof HabitosRoute
  '/integracoes': typeof IntegracoesRoute
  '/investimentos': typeof InvestimentosRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/mercado': typeof MercadoRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/parcelados': typeof ParceladosRoute
  '/resgate': typeof ResgateRoute
  '/tarefas': typeof TarefasRoute
  '/tarefas-domesticas': typeof TarefasDomesticasRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anotacoes': typeof AnotacoesRoute
  '/assinatura': typeof AssinaturaRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/faturas': typeof FaturasRoute
  '/fluxo': typeof FluxoRoute
  '/habitos': typeof HabitosRoute
  '/integracoes': typeof IntegracoesRoute
  '/investimentos': typeof InvestimentosRoute
  '/lista': typeof ListaRoute
  '/login': typeof LoginRoute
  '/mais': typeof MaisRoute
  '/mercado': typeof MercadoRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamento': typeof OrcamentoRoute
  '/parcelados': typeof ParceladosRoute
  '/resgate': typeof ResgateRoute
  '/tarefas': typeof TarefasRoute
  '/tarefas-domesticas': typeof TarefasDomesticasRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/anotacoes'
    | '/assinatura'
    | '/calendario'
    | '/configuracoes'
    | '/custos-fixos'
    | '/faturas'
    | '/fluxo'
    | '/habitos'
    | '/integracoes'
    | '/investimentos'
    | '/lista'
    | '/login'
    | '/mais'
    | '/mercado'
    | '/metas'
    | '/onboarding'
    | '/orcamento'
    | '/parcelados'
    | '/resgate'
    | '/tarefas'
    | '/tarefas-domesticas'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/anotacoes'
    | '/assinatura'
    | '/calendario'
    | '/configuracoes'
    | '/custos-fixos'
    | '/faturas'
    | '/fluxo'
    | '/habitos'
    | '/integracoes'
    | '/investimentos'
    | '/lista'
    | '/login'
    | '/mais'
    | '/mercado'
    | '/metas'
    | '/onboarding'
    | '/orcamento'
    | '/parcelados'
    | '/resgate'
    | '/tarefas'
    | '/tarefas-domesticas'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/anotacoes'
    | '/assinatura'
    | '/calendario'
    | '/configuracoes'
    | '/custos-fixos'
    | '/faturas'
    | '/fluxo'
    | '/habitos'
    | '/integracoes'
    | '/investimentos'
    | '/lista'
    | '/login'
    | '/mais'
    | '/mercado'
    | '/metas'
    | '/onboarding'
    | '/orcamento'
    | '/parcelados'
    | '/resgate'
    | '/tarefas'
    | '/tarefas-domesticas'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnotacoesRoute: typeof AnotacoesRoute
  AssinaturaRoute: typeof AssinaturaRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosFixosRoute: typeof CustosFixosRoute
  FaturasRoute: typeof FaturasRoute
  FluxoRoute: typeof FluxoRoute
  HabitosRoute: typeof HabitosRoute
  IntegracoesRoute: typeof IntegracoesRoute
  InvestimentosRoute: typeof InvestimentosRoute
  ListaRoute: typeof ListaRoute
  LoginRoute: typeof LoginRoute
  MaisRoute: typeof MaisRoute
  MercadoRoute: typeof MercadoRoute
  MetasRoute: typeof MetasRoute
  OnboardingRoute: typeof OnboardingRoute
  OrcamentoRoute: typeof OrcamentoRoute
  ParceladosRoute: typeof ParceladosRoute
  ResgateRoute: typeof ResgateRoute
  TarefasRoute: typeof TarefasRoute
  TarefasDomesticasRoute: typeof TarefasDomesticasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos-fixos': {
      id: '/custos-fixos'
      path: '/custos-fixos'
      fullPath: '/custos-fixos'
      preLoaderRoute: typeof CustosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelados': {
      id: '/parcelados'
      path: '/parcelados'
      fullPath: '/parcelados'
      preLoaderRoute: typeof ParceladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resgate': {
      id: '/resgate'
      path: '/resgate'
      fullPath: '/resgate'
      preLoaderRoute: typeof ResgateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas-domesticas': {
      id: '/tarefas-domesticas'
      path: '/tarefas-domesticas'
      fullPath: '/tarefas-domesticas'
      preLoaderRoute: typeof TarefasDomesticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnotacoesRoute: AnotacoesRoute,
  AssinaturaRoute: AssinaturaRoute,
  CalendarioRoute: CalendarioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosFixosRoute: CustosFixosRoute,
  FaturasRoute: FaturasRoute,
  FluxoRoute: FluxoRoute,
  HabitosRoute: HabitosRoute,
  IntegracoesRoute: IntegracoesRoute,
  InvestimentosRoute: InvestimentosRoute,
  ListaRoute: ListaRoute,
  LoginRoute: LoginRoute,
  MaisRoute: MaisRoute,
  MercadoRoute: MercadoRoute,
  MetasRoute: MetasRoute,
  OnboardingRoute: OnboardingRoute,
  OrcamentoRoute: OrcamentoRoute,
  ParceladosRoute: ParceladosRoute,
  ResgateRoute: ResgateRoute,
  TarefasRoute: TarefasRoute,
  TarefasDomesticasRoute: TarefasDomesticasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
