/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CustosFixosRouteImport } from './routes/custos-fixos'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as ParceladosRouteImport } from './routes/parcelados'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosFixosRoute = CustosFixosRouteImport.update({
  id: '/custos-fixos',
  path: '/custos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceladosRoute = ParceladosRouteImport.update({
  id: '/parcelados',
  path: '/parcelados',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/calendario': typeof CalendarioRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/faturas': typeof FaturasRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/lista': typeof ListaRoute
  '/mercado': typeof MercadoRoute
  '/metas': typeof MetasRoute
  '/orcamento': typeof OrcamentoRoute
  '/parcelados': typeof ParceladosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/calendario': typeof CalendarioRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/faturas': typeof FaturasRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/lista': typeof ListaRoute
  '/mercado': typeof MercadoRoute
  '/metas': typeof MetasRoute
  '/orcamento': typeof OrcamentoRoute
  '/parcelados': typeof ParceladosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/calendario': typeof CalendarioRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/faturas': typeof FaturasRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/lista': typeof ListaRoute
  '/mercado': typeof MercadoRoute
  '/metas': typeof MetasRoute
  '/orcamento': typeof OrcamentoRoute
  '/parcelados': typeof ParceladosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/calendario'
    | '/custos-fixos'
    | '/faturas'
    | '/fluxo'
    | '/investimentos'
    | '/lista'
    | '/mercado'
    | '/metas'
    | '/orcamento'
    | '/parcelados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/calendario'
    | '/custos-fixos'
    | '/faturas'
    | '/fluxo'
    | '/investimentos'
    | '/lista'
    | '/mercado'
    | '/metas'
    | '/orcamento'
    | '/parcelados'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/calendario'
    | '/custos-fixos'
    | '/faturas'
    | '/fluxo'
    | '/investimentos'
    | '/lista'
    | '/mercado'
    | '/metas'
    | '/orcamento'
    | '/parcelados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CalendarioRoute: typeof CalendarioRoute
  CustosFixosRoute: typeof CustosFixosRoute
  FaturasRoute: typeof FaturasRoute
  FluxoRoute: typeof FluxoRoute
  InvestimentosRoute: typeof InvestimentosRoute
  ListaRoute: typeof ListaRoute
  MercadoRoute: typeof MercadoRoute
  MetasRoute: typeof MetasRoute
  OrcamentoRoute: typeof OrcamentoRoute
  ParceladosRoute: typeof ParceladosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos-fixos': {
      id: '/custos-fixos'
      path: '/custos-fixos'
      fullPath: '/custos-fixos'
      preLoaderRoute: typeof CustosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelados': {
      id: '/parcelados'
      path: '/parcelados'
      fullPath: '/parcelados'
      preLoaderRoute: typeof ParceladosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CalendarioRoute: CalendarioRoute,
  CustosFixosRoute: CustosFixosRoute,
  FaturasRoute: FaturasRoute,
  FluxoRoute: FluxoRoute,
  InvestimentosRoute: InvestimentosRoute,
  ListaRoute: ListaRoute,
  MercadoRoute: MercadoRoute,
  MetasRoute: MetasRoute,
  OrcamentoRoute: OrcamentoRoute,
  ParceladosRoute: ParceladosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
