create schema if not exists private;
alter table public.household_payment_methods add column if not exists account_id uuid;
alter table public.transactions add column if not exists account_id uuid;
alter table public.transactions add column if not exists source_type text;
alter table public.transactions add column if not exists source_id uuid;
alter table public.transactions add column if not exists source_index integer;
alter table public.transactions add column if not exists source_total integer;
alter table public.transactions add column if not exists source_period text;
alter table public.household_payment_methods drop constraint if exists household_payment_methods_account_id_fkey;
alter table public.household_payment_methods add constraint household_payment_methods_account_id_fkey foreign key (account_id) references public.household_accounts(id) on delete set null;
alter table public.transactions drop constraint if exists transactions_account_id_fkey;
alter table public.transactions add constraint transactions_account_id_fkey foreign key (account_id) references public.household_accounts(id) on delete set null;
create unique index if not exists transactions_generated_source_uq on public.transactions(household_id,source_type,source_id,source_index) where source_type is not null and source_id is not null and source_index is not null;
create index if not exists transactions_financial_source_idx on public.transactions(household_id,source_type,source_id);
create index if not exists transactions_card_date_idx on public.transactions(household_id,card_id,date);
alter table public.fixed_cost_payments drop constraint if exists fixed_cost_payments_period_uq;
alter table public.fixed_cost_payments add constraint fixed_cost_payments_period_uq unique (household_id,fixed_cost_id,period);

create or replace function private.normalize_transaction_payment_final() returns trigger language plpgsql security definer set search_path='' as $$ declare p record; c record; begin if new.payment_method_id is not null then select * into p from public.household_payment_methods where id=new.payment_method_id and household_id=new.household_id; if p.id is not null then new.pay_method:=p.kind;new.payment_method_name:=p.name;new.card_id:=coalesce(new.card_id,p.card_id);new.account_id:=coalesce(new.account_id,p.account_id);end if; elsif new.payment_method_name is not null then select * into p from public.household_payment_methods where household_id=new.household_id and upper(name)=upper(new.payment_method_name) limit 1;if p.id is not null then new.payment_method_id:=p.id;new.pay_method:=p.kind;new.payment_method_name:=p.name;new.card_id:=coalesce(new.card_id,p.card_id);new.account_id:=coalesce(new.account_id,p.account_id);end if;end if;if new.card_id is not null then select * into c from public.cards where id=new.card_id and household_id=new.household_id;if c.id is not null then new.pay_method:='CREDITO';new.card_name:=c.name;end if;end if;return new;end $$;
drop trigger if exists trg_normalize_transaction_payment on public.transactions;
create trigger trg_normalize_transaction_payment before insert or update on public.transactions for each row execute function private.normalize_transaction_payment_final();

create or replace function private.sync_card_invoice_final(p_household_id uuid,p_card_id uuid,p_period text) returns void language plpgsql security definer set search_path='' as $$ declare v_total numeric:=0;v_invoice_id uuid;begin if p_card_id is null or p_period is null then return;end if;select coalesce(sum(t.amount),0) into v_total from public.transactions t where t.household_id=p_household_id and t.card_id=p_card_id and t.type='DESPESA' and public.card_invoice_period(p_card_id,t.date)=p_period;select id into v_invoice_id from public.invoices where household_id=p_household_id and card_id=p_card_id and period=p_period limit 1;if v_total>0 then if v_invoice_id is null then insert into public.invoices(household_id,card_id,period,total,status) values(p_household_id,p_card_id,p_period,v_total,'ABERTA');else update public.invoices set total=v_total,updated_at=now() where id=v_invoice_id and status<>'PAGA';end if;elsif v_invoice_id is not null and (select status from public.invoices where id=v_invoice_id)<>'PAGA' then delete from public.invoices where id=v_invoice_id;end if;end $$;
create or replace function private.sync_transaction_invoice_final() returns trigger language plpgsql security definer set search_path='' as $$ begin if tg_op in ('UPDATE','DELETE') and old.card_id is not null then perform private.sync_card_invoice_final(old.household_id,old.card_id,public.card_invoice_period(old.card_id,old.date));end if;if tg_op<>'DELETE' and new.card_id is not null and new.type='DESPESA' then perform private.sync_card_invoice_final(new.household_id,new.card_id,public.card_invoice_period(new.card_id,new.date));end if;return coalesce(new,old);end $$;
drop trigger if exists trg_sync_transaction_invoice_after on public.transactions;
create trigger trg_sync_transaction_invoice_after after insert or update or delete on public.transactions for each row execute function private.sync_transaction_invoice_final();

create or replace function private.sync_installment_transactions_final() returns trigger language plpgsql security definer set search_path='' as $$ declare v_count int;v_idx int;v_amount numeric;v_date date;begin if tg_op in ('UPDATE','DELETE') then delete from public.transactions where household_id=old.household_id and source_type='INSTALLMENT' and source_id=old.id;end if;if tg_op<>'DELETE' then v_count:=greatest(new.installments_count,1);for v_idx in 1..v_count loop v_date:=(new.purchase_date+make_interval(months=>v_idx-1))::date;if v_idx<v_count then v_amount:=round((new.total_amount/v_count)::numeric,2);else v_amount:=new.total_amount-round((new.total_amount/v_count)::numeric,2)*(v_count-1);end if;insert into public.transactions(household_id,date,description,amount,type,category,pay_method,card_name,responsible,installment_current,installment_total,is_fixed,paid,payment_method_name,payment_method_id,card_id,source_type,source_id,source_index,source_total,source_period) values(new.household_id,v_date,new.name,v_amount,'DESPESA',new.category,new.pay_method,new.card_name,new.responsible,v_idx,v_count,false,v_idx<=greatest(new.paid_count,0),new.payment_method_name,new.payment_method_id,new.card_id,'INSTALLMENT',new.id,v_idx,v_count,to_char(v_date,'YYYY-MM')) on conflict (household_id,source_type,source_id,source_index) where source_type is not null and source_id is not null and source_index is not null do update set date=excluded.date,description=excluded.description,amount=excluded.amount,category=excluded.category,pay_method=excluded.pay_method,card_name=excluded.card_name,responsible=excluded.responsible,installment_current=excluded.installment_current,installment_total=excluded.installment_total,paid=excluded.paid,payment_method_name=excluded.payment_method_name,payment_method_id=excluded.payment_method_id,card_id=excluded.card_id,source_total=excluded.source_total,source_period=excluded.source_period;end loop;end if;return coalesce(new,old);end $$;
drop trigger if exists trg_sync_installment_transactions_final on public.installments;
create trigger trg_sync_installment_transactions_final after insert or update or delete on public.installments for each row execute function private.sync_installment_transactions_final();

create or replace function private.sync_fixed_cost_transactions_final() returns trigger language plpgsql security definer set search_path='' as $$ declare i int;v_date date;v_month int;v_period text;v_paid boolean;begin if tg_op in ('UPDATE','DELETE') then delete from public.transactions where household_id=old.household_id and source_type='FIXED_COST' and source_id=old.id;end if;if tg_op<>'DELETE' then for i in 0..23 loop v_date:=(date_trunc('month',current_date)::date+make_interval(months=>i))::date;v_month:=extract(month from v_date)::int;if coalesce(new.months[v_month],false) then v_date:=make_date(extract(year from v_date)::int,v_month,least(greatest(new.due_day,1),extract(day from(date_trunc('month',v_date)+interval '1 month - 1 day'))::int));v_period:=to_char(v_date,'YYYY-MM');select paid into v_paid from public.fixed_cost_payments where household_id=new.household_id and fixed_cost_id=new.id and period=v_period limit 1;insert into public.transactions(household_id,date,description,amount,type,category,pay_method,card_name,responsible,is_fixed,paid,payment_method_name,payment_method_id,card_id,source_type,source_id,source_index,source_total,source_period) values(new.household_id,v_date,new.name,new.amount,'DESPESA',new.category,new.pay_method,new.card_name,new.responsible,true,coalesce(v_paid,false),new.payment_method_name,new.payment_method_id,new.card_id,'FIXED_COST',new.id,i+1,24,v_period) on conflict (household_id,source_type,source_id,source_index) where source_type is not null and source_id is not null and source_index is not null do update set date=excluded.date,description=excluded.description,amount=excluded.amount,category=excluded.category,pay_method=excluded.pay_method,card_name=excluded.card_name,responsible=excluded.responsible,paid=excluded.paid,payment_method_name=excluded.payment_method_name,payment_method_id=excluded.payment_method_id,card_id=excluded.card_id,source_period=excluded.source_period;end if;end loop;end if;return coalesce(new,old);end $$;
drop trigger if exists trg_sync_fixed_cost_transactions_final on public.fixed_costs;
create trigger trg_sync_fixed_cost_transactions_final after insert or update or delete on public.fixed_costs for each row execute function private.sync_fixed_cost_transactions_final();
create or replace function private.sync_fixed_cost_payment_transaction_final() returns trigger language plpgsql security definer set search_path='' as $$ begin update public.transactions set paid=new.paid,updated_at=now() where household_id=new.household_id and source_type='FIXED_COST' and source_id=new.fixed_cost_id and source_period=new.period;return new;end $$;
drop trigger if exists trg_sync_fixed_cost_payment_transaction_final on public.fixed_cost_payments;
create trigger trg_sync_fixed_cost_payment_transaction_final after insert or update on public.fixed_cost_payments for each row execute function private.sync_fixed_cost_payment_transaction_final();
revoke all on schema private from public;
revoke execute on all functions in schema private from public,anon,authenticated;
