-- Performance indexes for business foreign keys and remaining FK coverage.
create index if not exists idx_business_accounts_payable_business_id on public.business_accounts_payable(business_id);
create index if not exists idx_business_accounts_payable_household_id on public.business_accounts_payable(household_id);
create index if not exists idx_business_accounts_payable_supplier_id on public.business_accounts_payable(supplier_id);
create index if not exists idx_business_accounts_receivable_business_id on public.business_accounts_receivable(business_id);
create index if not exists idx_business_accounts_receivable_household_id on public.business_accounts_receivable(household_id);
create index if not exists idx_business_cash_entries_business_id on public.business_cash_entries(business_id);
create index if not exists idx_business_cash_entries_household_id on public.business_cash_entries(household_id);
create index if not exists idx_business_ingredients_business_id on public.business_ingredients(business_id);
create index if not exists idx_business_ingredients_household_id on public.business_ingredients(household_id);
create index if not exists idx_business_ingredients_supplier_id on public.business_ingredients(supplier_id);
create index if not exists idx_business_invoices_business_id on public.business_invoices(business_id);
create index if not exists idx_business_invoices_household_id on public.business_invoices(household_id);
create index if not exists idx_business_productions_business_id on public.business_productions(business_id);
create index if not exists idx_business_productions_household_id on public.business_productions(household_id);
create index if not exists idx_business_productions_product_id on public.business_productions(product_id);
create index if not exists idx_business_products_business_id on public.business_products(business_id);
create index if not exists idx_business_products_household_id on public.business_products(household_id);
create index if not exists idx_business_products_recipe_id on public.business_products(recipe_id);
create index if not exists idx_business_purchase_items_business_id on public.business_purchase_items(business_id);
create index if not exists idx_business_purchase_items_household_id on public.business_purchase_items(household_id);
create index if not exists idx_business_purchase_items_ingredient_id on public.business_purchase_items(ingredient_id);
create index if not exists idx_business_purchase_items_purchase_id on public.business_purchase_items(purchase_id);
create index if not exists idx_business_purchases_business_id on public.business_purchases(business_id);
create index if not exists idx_business_purchases_household_id on public.business_purchases(household_id);
create index if not exists idx_business_purchases_supplier_id on public.business_purchases(supplier_id);
create index if not exists idx_business_quotes_business_id on public.business_quotes(business_id);
create index if not exists idx_business_quotes_household_id on public.business_quotes(household_id);
create index if not exists idx_business_recipe_items_business_id on public.business_recipe_items(business_id);
create index if not exists idx_business_recipe_items_household_id on public.business_recipe_items(household_id);
create index if not exists idx_business_recipe_items_ingredient_id on public.business_recipe_items(ingredient_id);
create index if not exists idx_business_recipe_items_recipe_id on public.business_recipe_items(recipe_id);
create index if not exists idx_business_recipes_business_id on public.business_recipes(business_id);
create index if not exists idx_business_recipes_household_id on public.business_recipes(household_id);
create index if not exists idx_business_sale_items_business_id on public.business_sale_items(business_id);
create index if not exists idx_business_sale_items_household_id on public.business_sale_items(household_id);
create index if not exists idx_business_sale_items_product_id on public.business_sale_items(product_id);
create index if not exists idx_business_sale_items_sale_id on public.business_sale_items(sale_id);
create index if not exists idx_business_sales_business_id on public.business_sales(business_id);
create index if not exists idx_business_sales_household_id on public.business_sales(household_id);
create index if not exists idx_business_stock_movements_business_id on public.business_stock_movements(business_id);
create index if not exists idx_business_stock_movements_household_id on public.business_stock_movements(household_id);
create index if not exists idx_business_stock_movements_ingredient_id on public.business_stock_movements(ingredient_id);
create index if not exists idx_business_suppliers_business_id on public.business_suppliers(business_id);
create index if not exists idx_business_suppliers_household_id on public.business_suppliers(household_id);
create index if not exists idx_businesses_household_id on public.businesses(household_id);
create index if not exists idx_cards_account_id on public.cards(account_id);
create index if not exists idx_google_calendar_connections_household_id on public.google_calendar_connections(household_id);
create index if not exists idx_google_calendar_event_links_household_id on public.google_calendar_event_links(household_id);

-- Keep the canonical existing business indexes; remove duplicates introduced by older migrations.
drop index if exists public.idx_business_ingredients_business;
drop index if exists public.idx_business_production_business;
drop index if exists public.idx_business_products_business;
drop index if exists public.idx_business_recipe_items_recipe;
drop index if exists public.idx_business_recipes_business;
drop index if exists public.idx_business_sales_business;
drop index if exists public.idx_business_tables_household;
